package com.fise.xiaoyu.DB.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here

import android.text.TextUtils;
import android.util.Log;

import com.fise.xiaoyu.config.DBConstant;
import com.fise.xiaoyu.imservice.entity.SearchElement;
import com.fise.xiaoyu.utils.pinyin.PinYin.PinYinElement;

// KEEP INCLUDES END

/**
 * 设备的任务(例如上课模式,爱心提醒等)
 * 
 */
public class DeviceCrontab {

	protected Long id;
	public int task_id;
	public int device_id;
	public int task_type;
	public String task_name;
	public String task_param;
	public String begin_time;
	public String end_time = " ";
	public int status;
	public int repeat_mode;
	public String repeat_value;

	public DeviceCrontab() {

	}

	public DeviceCrontab(Long id) {
		this.id = id;
	}

	public DeviceCrontab(Long id, int task_id, int device_id, int task_type,
			String task_name, String task_param,String begin_time,String end_time,int status,int repeat_mode,String repeat_value) {
		this.id = id;
		
		this.task_id = task_id;
		this.device_id = device_id;
		this.task_type = task_type;
		this.task_name = task_name;
		this.task_param = task_param;

		this.begin_time = begin_time;
		this.end_time = end_time;
		this.status = status;
		
		this.repeat_mode = repeat_mode;
		this.repeat_value = repeat_value;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	
    public int getTaskId() {
        return task_id;
    }

    public void setTaskId(int task_id) {
        this.task_id = task_id;
    }
  
    
    public int getDeviceId() {
        return device_id;
    }

    public void setDeviceId(int device_id) {
        this.device_id = device_id;
    }
   
    public int getTaskType() {
        return task_type;
    }

    public void setTaskType(int task_type) {
        this.task_type = task_type;
    }
    
     
    public String getTaskName() {
		return task_name;
	}

	public void setTaskName(String task_name) {
		this.task_name = task_name;
	}
	
	 
    public String getTaskParam() {
		return task_param;
	}

	public void setTaskParam(String task_param) {
		this.task_param = task_param;
	}
	
	
	
    public String getBeginTime() {
        return begin_time;
    }

    public void setBeginTime(String begin_time) {
        this.begin_time = begin_time;
    }
    
    
    public String getEndTime() {
        return end_time;
    }

    public void setEndTime(String end_time) {
        this.end_time = end_time;
    }

	
    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }
    
    
    public int getRepeatMode() {
        return repeat_mode;
    }

    public void setRepeatMode(int repeat_mode) {
        this.repeat_mode = repeat_mode;
    }
    
    
    public String getRepeatValue() {
		return repeat_value;
	}

	public void setRepeatValue(String repeat_value) {
		this.repeat_value = repeat_value;
	}
    
     
	@Override
	public boolean equals(Object o) {
		if (this == o)
			return true;
		if (!(o instanceof DeviceCrontab))
			return false;

		DeviceCrontab entity = (DeviceCrontab) o;

		if (task_id != entity.task_id)
			return false;
		if (device_id != entity.device_id)
			return false;
		if (task_type != entity.task_type)
			return false;
		
		if (!task_name.equals(entity.task_name))
			return false; 
		if (!task_param.equals(entity.task_param))
			return false;
		 
		if (begin_time != entity.begin_time)
			return false; 
		if (end_time != entity.end_time)
			return false;
		if (status != entity.status)
			return false;
		if (repeat_mode != entity.repeat_mode)
			return false;
		   
		if (!repeat_value.equals(entity.repeat_value))
			return false;
		 
		
		
		return true;
	}

	// KEEP METHODS END

}
