package com.fise.marechat.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.fise.marechat.bean.dao.CenterAlert;
import com.fise.marechat.bean.dao.CenterClock;
import com.fise.marechat.bean.dao.CenterCounter;
import com.fise.marechat.bean.dao.CenterSettings;
import com.fise.marechat.bean.dao.ClockFormat;
import com.fise.marechat.bean.dao.MessagePhrase;
import com.fise.marechat.bean.dao.PhoneBook;
import com.fise.marechat.bean.dao.PhoneContractor;
import com.fise.marechat.bean.dao.StepHistory;

import com.fise.marechat.dao.CenterAlertDao;
import com.fise.marechat.dao.CenterClockDao;
import com.fise.marechat.dao.CenterCounterDao;
import com.fise.marechat.dao.CenterSettingsDao;
import com.fise.marechat.dao.ClockFormatDao;
import com.fise.marechat.dao.MessagePhraseDao;
import com.fise.marechat.dao.PhoneBookDao;
import com.fise.marechat.dao.PhoneContractorDao;
import com.fise.marechat.dao.StepHistoryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig centerAlertDaoConfig;
    private final DaoConfig centerClockDaoConfig;
    private final DaoConfig centerCounterDaoConfig;
    private final DaoConfig centerSettingsDaoConfig;
    private final DaoConfig clockFormatDaoConfig;
    private final DaoConfig messagePhraseDaoConfig;
    private final DaoConfig phoneBookDaoConfig;
    private final DaoConfig phoneContractorDaoConfig;
    private final DaoConfig stepHistoryDaoConfig;

    private final CenterAlertDao centerAlertDao;
    private final CenterClockDao centerClockDao;
    private final CenterCounterDao centerCounterDao;
    private final CenterSettingsDao centerSettingsDao;
    private final ClockFormatDao clockFormatDao;
    private final MessagePhraseDao messagePhraseDao;
    private final PhoneBookDao phoneBookDao;
    private final PhoneContractorDao phoneContractorDao;
    private final StepHistoryDao stepHistoryDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        centerAlertDaoConfig = daoConfigMap.get(CenterAlertDao.class).clone();
        centerAlertDaoConfig.initIdentityScope(type);

        centerClockDaoConfig = daoConfigMap.get(CenterClockDao.class).clone();
        centerClockDaoConfig.initIdentityScope(type);

        centerCounterDaoConfig = daoConfigMap.get(CenterCounterDao.class).clone();
        centerCounterDaoConfig.initIdentityScope(type);

        centerSettingsDaoConfig = daoConfigMap.get(CenterSettingsDao.class).clone();
        centerSettingsDaoConfig.initIdentityScope(type);

        clockFormatDaoConfig = daoConfigMap.get(ClockFormatDao.class).clone();
        clockFormatDaoConfig.initIdentityScope(type);

        messagePhraseDaoConfig = daoConfigMap.get(MessagePhraseDao.class).clone();
        messagePhraseDaoConfig.initIdentityScope(type);

        phoneBookDaoConfig = daoConfigMap.get(PhoneBookDao.class).clone();
        phoneBookDaoConfig.initIdentityScope(type);

        phoneContractorDaoConfig = daoConfigMap.get(PhoneContractorDao.class).clone();
        phoneContractorDaoConfig.initIdentityScope(type);

        stepHistoryDaoConfig = daoConfigMap.get(StepHistoryDao.class).clone();
        stepHistoryDaoConfig.initIdentityScope(type);

        centerAlertDao = new CenterAlertDao(centerAlertDaoConfig, this);
        centerClockDao = new CenterClockDao(centerClockDaoConfig, this);
        centerCounterDao = new CenterCounterDao(centerCounterDaoConfig, this);
        centerSettingsDao = new CenterSettingsDao(centerSettingsDaoConfig, this);
        clockFormatDao = new ClockFormatDao(clockFormatDaoConfig, this);
        messagePhraseDao = new MessagePhraseDao(messagePhraseDaoConfig, this);
        phoneBookDao = new PhoneBookDao(phoneBookDaoConfig, this);
        phoneContractorDao = new PhoneContractorDao(phoneContractorDaoConfig, this);
        stepHistoryDao = new StepHistoryDao(stepHistoryDaoConfig, this);

        registerDao(CenterAlert.class, centerAlertDao);
        registerDao(CenterClock.class, centerClockDao);
        registerDao(CenterCounter.class, centerCounterDao);
        registerDao(CenterSettings.class, centerSettingsDao);
        registerDao(ClockFormat.class, clockFormatDao);
        registerDao(MessagePhrase.class, messagePhraseDao);
        registerDao(PhoneBook.class, phoneBookDao);
        registerDao(PhoneContractor.class, phoneContractorDao);
        registerDao(StepHistory.class, stepHistoryDao);
    }
    
    public void clear() {
        centerAlertDaoConfig.clearIdentityScope();
        centerClockDaoConfig.clearIdentityScope();
        centerCounterDaoConfig.clearIdentityScope();
        centerSettingsDaoConfig.clearIdentityScope();
        clockFormatDaoConfig.clearIdentityScope();
        messagePhraseDaoConfig.clearIdentityScope();
        phoneBookDaoConfig.clearIdentityScope();
        phoneContractorDaoConfig.clearIdentityScope();
        stepHistoryDaoConfig.clearIdentityScope();
    }

    public CenterAlertDao getCenterAlertDao() {
        return centerAlertDao;
    }

    public CenterClockDao getCenterClockDao() {
        return centerClockDao;
    }

    public CenterCounterDao getCenterCounterDao() {
        return centerCounterDao;
    }

    public CenterSettingsDao getCenterSettingsDao() {
        return centerSettingsDao;
    }

    public ClockFormatDao getClockFormatDao() {
        return clockFormatDao;
    }

    public MessagePhraseDao getMessagePhraseDao() {
        return messagePhraseDao;
    }

    public PhoneBookDao getPhoneBookDao() {
        return phoneBookDao;
    }

    public PhoneContractorDao getPhoneContractorDao() {
        return phoneContractorDao;
    }

    public StepHistoryDao getStepHistoryDao() {
        return stepHistoryDao;
    }

}
