package com.fise.xw.DB.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here

import android.text.TextUtils;
import android.util.Log;

import com.fise.xw.config.DBConstant;
import com.fise.xw.imservice.entity.SearchElement;
import com.fise.xw.utils.pinyin.PinYin.PinYinElement;
// KEEP INCLUDES END


/**
 *  白名单/紧急号码  数据
 * @author weileiguan
 *
 */
public class WhiteEntity {
 
	protected Long id; 
    protected String phone;  
    private int devId;
     
    public WhiteEntity() {
    	
    }

    public WhiteEntity(Long id) {
        this.id = id;
    }

    public WhiteEntity(Long id,String phone,int devId) {
    	 this.id = id;  
    	 this.phone = phone; 
    	 this.devId = devId; 
    }
 
     
    
    public Long getId() {
        return id;
    }

    public void setId(Long id) { 
        this.id = id;
    }
     
    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }
    
    
    
    public int getDevId() {
        return devId;
    }

    public void setDevId(int devId) {
        this.devId = devId;
    }
  
  
 
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof WhiteEntity)) return false;

        WhiteEntity entity = (WhiteEntity) o; 
        
        if (!phone.equals(entity.phone)) return false; 
        if (devId != entity.devId) return false; 
        
        return true;
    }
 

    // KEEP METHODS END

}
