package com.fise.xw.DB.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.fise.xw.DB.entity.GroupEntity;
import com.fise.xw.DB.entity.WhiteEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 *  存报警号码的表(可能后续有添加属性)
*/
public class AlarmDao extends AbstractDao<WhiteEntity, Long> {

    public static final String TABLENAME = "AlarmListInfo";

    /**
     * Properties of entity GroupEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id"); 
        public final static Property Phone = new Property(1, String.class, "Phone", false, "PHONE");
        public final static Property devId = new Property(2, int.class, "devId", false, "DEV_ID");
        
    };


    public AlarmDao(DaoConfig config) {
        super(config);
    }
    
    public AlarmDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }   

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'AlarmListInfo' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id  
                "'PHONE' TEXT NOT NULL ," + // 4: phone
                "'DEV_ID' INTEGER NOT NULL );"); // 2: devid
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "WHITE TABLE " + (ifExists ? "IF EXISTS " : "") + "'AlarmListInfo'";
        db.execSQL(sql);
    }
 
    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, WhiteEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }  
        stmt.bindString(2, entity.getPhone()); 
        stmt.bindLong(3, entity.getDevId());
         
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

   
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, WhiteEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0)); 
        entity.setPhone(cursor.getString(offset + 1)); 
        entity.setDevId(cursor.getInt(offset + 2)); 
        
     }
    
    
    /** @inheritdoc */
    @Override
    public WhiteEntity readEntity(Cursor cursor, int offset) {
    	WhiteEntity entity = new WhiteEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id  
            cursor.getString(offset + 1), // phone 
            cursor.getInt(offset + 2) // devId 
        );
        return entity;
    }
     
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(WhiteEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(WhiteEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }


}
