package com.fise.xiaoyu.ui.widget.message;

/**
 * RenderType
 */
public enum  RenderType {
    MESSAGE_TYPE_INVALID,
    MESSAGE_TYPE_MINE_TETX ,
    MESSAGE_TYPE_MINE_GIF ,
    MESSAGE_TYPE_MINE_IMAGE,
    MESSAGE_TYPE_MINE_GIF_IMAGE,
    MESSAGE_TYPE_MINE_AUDIO,
    MESSAGE_TYPE_OTHER_TEXT,
    MESSAGE_TYPE_OTHER_GIF,
    MESSAGE_TYPE_OTHER_IMAGE,
    MESSAGE_TYPE_OTHER_GIF_IMAGE,
    MESSAGE_TYPE_OTHER_AUDIO,
    MESSAGE_TYPE_TIME_TITLE,
    MESSAGE_TYPE_TEXT_TITLE,
    MESSAGE_TYPE_WEI_FRIENDS,
    MESSAGE_TYPE_NOTICE,
    MESSAGE_TYPE_CARD,
    MESSAGE_TYPE_MINE_VEDIO,
    MESSAGE_TYPE_OTHER_VEDIO,
    
    MESSAGE_TYPE_MINE_CARD,
    MESSAGE_TYPE_OTHER_CARD,
    
    MESSAGE_TYPE_MINE_POSTION,
    MESSAGE_TYPE_OTHER_POSTION,
    MESSAGE_TYPE_OTHER_ADDFRIENDS,
    MESSAGE_TYPE_OTHER_DEV ,
    MESSAGE_TYPE_OTHER_LINE_VEDIO,
    MESSAGE_TYPE_MINE_LINE_VEDIO
      
}
