package com.fise.xiaoyu.DB.dao;

import android.database.sqlite.SQLiteDatabase;

import com.fise.xiaoyu.DB.entity.DeviceCrontab;
import com.fise.xiaoyu.DB.entity.DeviceEntity;
import com.fise.xiaoyu.DB.entity.DeviceTrajectory;
import com.fise.xiaoyu.DB.entity.FamilyConcernEntity;
import com.fise.xiaoyu.DB.entity.GroupEntity;
import com.fise.xiaoyu.DB.entity.GroupNickEntity;
import com.fise.xiaoyu.DB.entity.GroupVersion;
import com.fise.xiaoyu.DB.entity.MessageEntity;
import com.fise.xiaoyu.DB.entity.RankingListEntity;
import com.fise.xiaoyu.DB.entity.ReqFriendsEntity;
import com.fise.xiaoyu.DB.entity.SessionEntity;
import com.fise.xiaoyu.DB.entity.StepData;
import com.fise.xiaoyu.DB.entity.StepRanking;
import com.fise.xiaoyu.DB.entity.SystemConfigEntity;
import com.fise.xiaoyu.DB.entity.UserEntity;
import com.fise.xiaoyu.DB.entity.WeiEntity;
import com.fise.xiaoyu.DB.entity.WhiteEntity;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

	private final DaoConfig userDaoConfig;
	private final DaoConfig groupDaoConfig;
	private final DaoConfig messageDaoConfig;
	private final DaoConfig sessionDaoConfig;
	private final DaoConfig reqFriendsDaoConfig;
	private final DaoConfig friendsDaoConfig;
	private final DaoConfig RelationsUserConfig;
	private final DaoConfig DeviceConfig;
	private final DaoConfig groupWeiDaoConfig;
	private final DaoConfig AuthUserDaoConfig;
	private final DaoConfig WhiteListDaoConfig;
	private final DaoConfig alarmDaoConfig;
	private final DaoConfig deviceConfigureConfig;
	private final DaoConfig reqUnMessageConfig;
	private final DaoConfig GroupVersionConfig;
	private final DaoConfig blackListConfig;
	private final DaoConfig trajectoryConfig;
	private final DaoConfig userFriendsConfig;
	private final DaoConfig groupNickConfig;
	private final DaoConfig reqUnYuFriendsConfig;


	private final DaoConfig familyConcernConfig;
	private final DaoConfig taskConfig;
	private final DaoConfig yuReqFriendsConfig;
	private final DaoConfig yuRefuseConfig;


	private final DaoConfig parentUserConfig;
	private final DaoConfig stepRankingConfig;

	private final DaoConfig rankingListConfig;
	private final DaoConfig reqParentRefuseConfig;
	private final DaoConfig stepDataConfig;



	//private final DaoConfig firmwareConfig;

	// private final DaoConfig monitorDaoConfig;

	private final UserDao userDao;
	private final GroupDao groupDao;
	private final MessageDao messageDao;
	private final SessionDao sessionDao;
	private final ReqFriendsDao reqDao;
	private final UserFriendsDao userFriendsDao;
	private final YuReqFriendsDao yuReqFriendsDao;
	private final ParentRefuseDao parentRefuseDao;


	private final FriendsDao friendsDao;
	private final RelationsUserDao relationsDao;
	private final DeviceDao deviceDao;
	private final GroupWeiDao groupWeiDao;
	private final AuthUserDao authUserDao;
	private final WhiteListDao whiteListDao;
	private final AlarmDao alarmDao;
	private final DeviceConfigureDao deviceConfigure;
	private final ReqMessageDao reqUnMessageDao;
	private final ReqYuFriendsDao reqYuFriendsDao;
	private final ReqParentRefuseDao reqParentRefuseDao;


	private final GroupVersionDao groupVersion;
	private final BlackListDao blackListDao;
	private final DeviceTrajectoryDao trajectoryDao;
	private final GroupNickDao groupNickDao;

	private final SystemConfigDao systemConfigDao;
	private final DaoConfig systemConfig;

	private final FamilyConcernDao familyDao;
	private final TaskDao taskDao;
	private final ParentUserDao parentUserDao;
	private final StepRankingDao stepRankingDao;

	private final RankingListDao rankingListDao;
	private final StepDataDao stepDataDao;



	//private final  FirmwareDao firmwareDao;

	// private final MonitorUserDao monitorDao;

	public DaoSession(SQLiteDatabase db, IdentityScopeType type,
			Map<Class<? extends AbstractDao<?, ?>>, DaoConfig> daoConfigMap) {
		super(db);


		//本地计步的数据
		stepDataConfig = daoConfigMap.get(StepDataDao.class).clone();
		stepDataConfig.initIdentityScope(type);


		//管理员同意拒绝 的角标
		reqParentRefuseConfig = daoConfigMap.get(ReqParentRefuseDao.class).clone();
		reqParentRefuseConfig.initIdentityScope(type);


		//计步数据
		stepRankingConfig = daoConfigMap.get(StepRankingDao.class).clone();
		stepRankingConfig.initIdentityScope(type);

		//计步排行榜数据
		rankingListConfig = daoConfigMap.get(RankingListDao.class).clone();
		rankingListConfig.initIdentityScope(type);



		userDaoConfig = daoConfigMap.get(UserDao.class).clone();
		userDaoConfig.initIdentityScope(type);

		groupDaoConfig = daoConfigMap.get(GroupDao.class).clone();
		groupDaoConfig.initIdentityScope(type);

		messageDaoConfig = daoConfigMap.get(MessageDao.class).clone();
		messageDaoConfig.initIdentityScope(type);

		sessionDaoConfig = daoConfigMap.get(SessionDao.class).clone();
		sessionDaoConfig.initIdentityScope(type);

		reqFriendsDaoConfig = daoConfigMap.get(ReqFriendsDao.class).clone();
		reqFriendsDaoConfig.initIdentityScope(type);


		friendsDaoConfig = daoConfigMap.get(FriendsDao.class).clone();
		friendsDaoConfig.initIdentityScope(type);


		RelationsUserConfig = daoConfigMap.get(RelationsUserDao.class).clone();
		RelationsUserConfig.initIdentityScope(type);

		DeviceConfig = daoConfigMap.get(DeviceDao.class).clone();
		DeviceConfig.initIdentityScope(type);

		groupWeiDaoConfig = daoConfigMap.get(GroupWeiDao.class).clone();
		groupWeiDaoConfig.initIdentityScope(type);

		AuthUserDaoConfig = daoConfigMap.get(AuthUserDao.class).clone();
		AuthUserDaoConfig.initIdentityScope(type);

		WhiteListDaoConfig = daoConfigMap.get(WhiteListDao.class).clone();
		WhiteListDaoConfig.initIdentityScope(type);

		alarmDaoConfig = daoConfigMap.get(AlarmDao.class).clone();
		alarmDaoConfig.initIdentityScope(type);

		deviceConfigureConfig = daoConfigMap.get(DeviceConfigureDao.class).clone();
		deviceConfigureConfig.initIdentityScope(type);



		reqUnYuFriendsConfig = daoConfigMap.get(ReqYuFriendsDao.class).clone();
		reqUnYuFriendsConfig.initIdentityScope(type);


		reqUnMessageConfig = daoConfigMap.get(ReqMessageDao.class).clone();
		reqUnMessageConfig.initIdentityScope(type);

		GroupVersionConfig = daoConfigMap.get(GroupVersionDao.class).clone();
		GroupVersionConfig.initIdentityScope(type);

		// 黑名单
		blackListConfig = daoConfigMap.get(BlackListDao.class).clone();
		blackListConfig.initIdentityScope(type);

		// monitorDaoConfig = daoConfigMap.get(MonitorUserDao.class).clone();
		// monitorDaoConfig.initIdentityScope(type);

		// 黑名单
		trajectoryConfig = daoConfigMap.get(DeviceTrajectoryDao.class).clone();
		trajectoryConfig.initIdentityScope(type);

		// 位友请求
		userFriendsConfig = daoConfigMap.get(UserFriendsDao.class).clone();
		userFriendsConfig.initIdentityScope(type);

		groupNickConfig = daoConfigMap.get(GroupNickDao.class).clone();
		groupNickConfig.initIdentityScope(type);

		// 亲切关注身份信息
		familyConcernConfig = daoConfigMap.get(FamilyConcernDao.class).clone();
		familyConcernConfig.initIdentityScope(type);


		// 雨友请求列表
		yuReqFriendsConfig = daoConfigMap.get(YuReqFriendsDao.class).clone();
		yuReqFriendsConfig.initIdentityScope(type);


		// 管理员同意或者拒绝请求列表
		yuRefuseConfig = daoConfigMap.get(ParentRefuseDao.class).clone();
		yuRefuseConfig.initIdentityScope(type);


		// 系统配置
		systemConfig = daoConfigMap.get(SystemConfigDao.class).clone();
		systemConfig.initIdentityScope(type);

		// 任务/上课/爱心等配制信息
		taskConfig = daoConfigMap.get(TaskDao.class).clone();
		taskConfig.initIdentityScope(type);



		// 父母的信息表
		parentUserConfig = daoConfigMap.get(ParentUserDao.class).clone();
		parentUserConfig.initIdentityScope(type);



//		firmwareConfig = daoConfigMap.get(FirmwareDao.class).clone();
//		firmwareConfig.initIdentityScope(type);

		//管理员同意或者拒绝 角标
		reqParentRefuseDao = new ReqParentRefuseDao(reqParentRefuseConfig, this);


		//管理员同意或者拒绝
		parentRefuseDao = new ParentRefuseDao(yuRefuseConfig, this);


		//计步排行榜
		rankingListDao = new RankingListDao(rankingListConfig, this);

		// 雨友请求列表
		yuReqFriendsDao = new YuReqFriendsDao(yuReqFriendsConfig, this);

		// 父母的信息表
		parentUserDao = new ParentUserDao(parentUserConfig, this);

		// 计步排行榜数据
		stepRankingDao = new StepRankingDao(stepRankingConfig, this);


		trajectoryDao = new DeviceTrajectoryDao(trajectoryConfig, this);

		taskDao = new TaskDao(taskConfig, this); 
		userDao = new UserDao(userDaoConfig, this);
		groupDao = new GroupDao(groupDaoConfig, this);
		groupWeiDao = new GroupWeiDao(groupWeiDaoConfig, this);

		messageDao = new MessageDao(messageDaoConfig, this);
		sessionDao = new SessionDao(sessionDaoConfig, this);
		reqDao = new ReqFriendsDao(reqFriendsDaoConfig, this);
		friendsDao = new FriendsDao(friendsDaoConfig, this);
		relationsDao = new RelationsUserDao(RelationsUserConfig, this);
		deviceDao = new DeviceDao(DeviceConfig, this);
		authUserDao = new AuthUserDao(AuthUserDaoConfig, this);
		whiteListDao = new WhiteListDao(WhiteListDaoConfig, this);
		alarmDao = new AlarmDao(alarmDaoConfig, this);
		deviceConfigure = new DeviceConfigureDao(deviceConfigureConfig, this);

		reqYuFriendsDao = new ReqYuFriendsDao(reqUnYuFriendsConfig, this);
		reqUnMessageDao = new ReqMessageDao(reqUnMessageConfig, this);
		groupVersion = new GroupVersionDao(GroupVersionConfig, this);

		blackListDao = new BlackListDao(blackListConfig, this);
		userFriendsDao = new UserFriendsDao(userFriendsConfig, this);

		// monitorDao = new MonitorUserDao(monitorDaoConfig, this);
		groupNickDao = new GroupNickDao(groupNickConfig, this);

		familyDao = new FamilyConcernDao(familyConcernConfig, this);
		systemConfigDao = new SystemConfigDao(systemConfig, this);

		stepDataDao = new StepDataDao(stepDataConfig, this);


//		firmwareDao = new FirmwareDao(firmwareConfig, this);


		registerDao(UserEntity.class, userDao);
		registerDao(GroupEntity.class, groupDao);
		registerDao(GroupEntity.class, groupWeiDao);

		registerDao(MessageEntity.class, messageDao);
		registerDao(SessionEntity.class, sessionDao);
		registerDao(UserEntity.class, reqDao);
		registerDao(WeiEntity.class, userFriendsDao);
		registerDao(UserEntity.class, friendsDao);
		registerDao(UserEntity.class, relationsDao);
		registerDao(UserEntity.class, deviceDao);
		registerDao(UserEntity.class, authUserDao);
		registerDao(WhiteEntity.class, whiteListDao);
		registerDao(WhiteEntity.class, alarmDao);
		registerDao(DeviceEntity.class, deviceConfigure);
		registerDao(ReqFriendsEntity.class, reqUnMessageDao);
		registerDao(GroupVersion.class, groupVersion);

		registerDao(UserEntity.class, blackListDao);
		registerDao(DeviceTrajectory.class, trajectoryDao);

		registerDao(GroupNickEntity.class, groupNickDao);
		registerDao(FamilyConcernEntity.class, familyDao);
		registerDao(SystemConfigEntity.class, systemConfigDao);

		registerDao(DeviceCrontab.class, taskDao);
		registerDao(WeiEntity.class, yuReqFriendsDao);
		registerDao(ReqFriendsEntity.class, reqYuFriendsDao);
		registerDao(UserEntity.class, parentUserDao);
		registerDao(StepRanking.class, stepRankingDao);

		registerDao(RankingListEntity.class, rankingListDao);
		registerDao(WeiEntity.class, parentRefuseDao);
		registerDao(ReqFriendsEntity.class, reqParentRefuseDao);
		registerDao(StepData.class, stepDataDao);
//		registerDao(FirmwareInfo.class, firmwareDao);

		// registerDao(UserEntity.class, monitorDao);

	}

	public void clear() {
		userDaoConfig.getIdentityScope().clear();
		groupDaoConfig.getIdentityScope().clear();
		groupWeiDaoConfig.getIdentityScope().clear();

		messageDaoConfig.getIdentityScope().clear();
		sessionDaoConfig.getIdentityScope().clear();
		reqFriendsDaoConfig.getIdentityScope().clear();
		friendsDaoConfig.getIdentityScope().clear();

		RelationsUserConfig.getIdentityScope().clear();
		DeviceConfig.getIdentityScope().clear();
		AuthUserDaoConfig.getIdentityScope().clear();
		WhiteListDaoConfig.getIdentityScope().clear();
		alarmDaoConfig.getIdentityScope().clear();
		deviceConfigureConfig.getIdentityScope().clear();
		reqUnMessageConfig.getIdentityScope().clear();
		reqUnYuFriendsConfig.getIdentityScope().clear();

		GroupVersionConfig.getIdentityScope().clear();
		blackListConfig.getIdentityScope().clear();
		trajectoryConfig.getIdentityScope().clear();
		userFriendsConfig.getIdentityScope().clear();

		groupNickConfig.getIdentityScope().clear();
		familyConcernConfig.getIdentityScope().clear();
		systemConfig.getIdentityScope().clear();
		
		taskConfig.getIdentityScope().clear();
		yuReqFriendsConfig.getIdentityScope().clear();

		parentUserConfig.getIdentityScope().clear();
		stepRankingConfig.getIdentityScope().clear();

		rankingListConfig.getIdentityScope().clear();
		yuRefuseConfig.getIdentityScope().clear();

		reqParentRefuseConfig.getIdentityScope().clear();
		stepDataConfig.getIdentityScope().clear();


//		firmwareConfig.getIdentityScope().clear();
		// monitorDaoConfig.getIdentityScope().clear();
	}

	public ReqFriendsDao getReqFriends() {
		return reqDao;
	}

	public UserDao getUserDao() {
		return userDao;
	}

	public FriendsDao getFriendsDao() {
		return friendsDao;
	}


	public RelationsUserDao getRelationsDao() {
		return relationsDao;
	}

	public WhiteListDao getWhiteListDao() {
		return whiteListDao;
	}

	public AlarmDao getAlarmDao() {
		return alarmDao;
	}

	public DeviceConfigureDao getDeviceConfigureDao() {
		return deviceConfigure;
	}


	// public MonitorUserDao getMonitorUserDao() {
	// return monitorDao;
	// }

	public GroupDao getGroupDao() {
		return groupDao;
	}

	public MessageDao getMessageDao() {
		return messageDao;
	}

	public SessionDao getSessionDao() {
		return sessionDao;
	}

	public DeviceDao getDeviceDao() {
		return deviceDao;
	}

	public GroupWeiDao getGroupWeiDao() {
		return groupWeiDao;
	}

	public AuthUserDao getAuthUserDao() {
		return authUserDao;
	}

	public ReqMessageDao getReqUnMessageDao() {
		return reqUnMessageDao;
	}

	public GroupVersionDao getGroupVersionDao() {
		return groupVersion;
	}

	public BlackListDao getBlackListDao() {
		return blackListDao;
	}

	public DeviceTrajectoryDao getTrajectoryDao() {
		return trajectoryDao;
	}

	public UserFriendsDao getUserFriends() {
		return userFriendsDao;
	}

	public GroupNickDao getGroupNickDao() {
		return groupNickDao;
	}

	public FamilyConcernDao getFamilyConcernDao() {
		return familyDao;
	}

	public SystemConfigDao getSystemConfigDao() {
		return systemConfigDao;
	}
	
	
	public TaskDao getTaskDao() {
		return taskDao;
	}



	public YuReqFriendsDao getYuReqFriendsDao() {
		return yuReqFriendsDao;
	}

	public ReqYuFriendsDao getReqYuFriendsDao() {
		return reqYuFriendsDao;
	}

	public ParentUserDao getParentUserDao() {
		return parentUserDao;
	}

	public StepRankingDao getStepRankingDao() {
		return stepRankingDao;
	}

	public RankingListDao getRankingListDao() {
		return rankingListDao;
	}

	public ParentRefuseDao getParentRefuseDao() {
		return parentRefuseDao;
	}

	public ReqParentRefuseDao getReqParentRefuseDao() {
		return reqParentRefuseDao;
	}

	public StepDataDao getStepDataDao() {
		return stepDataDao;
	}


	//	public FirmwareDao getFirmwareDao() {
//		return firmwareDao;
//	}
}
