// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IM.Regist.proto

package com.fise.xiaoyu.protobuf;

public final class IMRegist {
  private IMRegist() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface IMRegistReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:IM.Regist.IMRegistReq)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required string account = 1;</code>
     *
     * <pre>
     *cmd id:	CID_REGIST_REQ_MSGSERVER	0x00ff
     * </pre>
     */
    boolean hasAccount();
    /**
     * <code>required string account = 1;</code>
     *
     * <pre>
     *cmd id:	CID_REGIST_REQ_MSGSERVER	0x00ff
     * </pre>
     */
    java.lang.String getAccount();
    /**
     * <code>required string account = 1;</code>
     *
     * <pre>
     *cmd id:	CID_REGIST_REQ_MSGSERVER	0x00ff
     * </pre>
     */
    com.google.protobuf.ByteString
        getAccountBytes();

    /**
     * <code>required string password = 2;</code>
     */
    boolean hasPassword();
    /**
     * <code>required string password = 2;</code>
     */
    java.lang.String getPassword();
    /**
     * <code>required string password = 2;</code>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();

    /**
     * <code>required .IM.BaseDefine.ClientType client_type = 3;</code>
     */
    boolean hasClientType();
    /**
     * <code>required .IM.BaseDefine.ClientType client_type = 3;</code>
     */
    com.fise.xiaoyu.protobuf.IMBaseDefine.ClientType getClientType();

    /**
     * <code>required string ime = 4;</code>
     */
    boolean hasIme();
    /**
     * <code>required string ime = 4;</code>
     */
    java.lang.String getIme();
    /**
     * <code>required string ime = 4;</code>
     */
    com.google.protobuf.ByteString
        getImeBytes();

    /**
     * <code>optional string province = 5;</code>
     */
    boolean hasProvince();
    /**
     * <code>optional string province = 5;</code>
     */
    java.lang.String getProvince();
    /**
     * <code>optional string province = 5;</code>
     */
    com.google.protobuf.ByteString
        getProvinceBytes();

    /**
     * <code>optional string city = 6;</code>
     */
    boolean hasCity();
    /**
     * <code>optional string city = 6;</code>
     */
    java.lang.String getCity();
    /**
     * <code>optional string city = 6;</code>
     */
    com.google.protobuf.ByteString
        getCityBytes();

    /**
     * <code>optional string country = 7;</code>
     */
    boolean hasCountry();
    /**
     * <code>optional string country = 7;</code>
     */
    java.lang.String getCountry();
    /**
     * <code>optional string country = 7;</code>
     */
    com.google.protobuf.ByteString
        getCountryBytes();

    /**
     * <code>optional string client_version = 8;</code>
     */
    boolean hasClientVersion();
    /**
     * <code>optional string client_version = 8;</code>
     */
    java.lang.String getClientVersion();
    /**
     * <code>optional string client_version = 8;</code>
     */
    com.google.protobuf.ByteString
        getClientVersionBytes();

    /**
     * <code>optional bytes attach_data = 20;</code>
     */
    boolean hasAttachData();
    /**
     * <code>optional bytes attach_data = 20;</code>
     */
    com.google.protobuf.ByteString getAttachData();
  }
  /**
   * Protobuf type {@code IM.Regist.IMRegistReq}
   */
  public static final class IMRegistReq extends
      com.google.protobuf.GeneratedMessageLite implements
      // @@protoc_insertion_point(message_implements:IM.Regist.IMRegistReq)
      IMRegistReqOrBuilder {
    // Use IMRegistReq.newBuilder() to construct.
    private IMRegistReq(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private IMRegistReq(boolean noInit) { this.unknownFields = com.google.protobuf.ByteString.EMPTY;}

    private static final IMRegistReq defaultInstance;
    public static IMRegistReq getDefaultInstance() {
      return defaultInstance;
    }

    public IMRegistReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.ByteString unknownFields;
    private IMRegistReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.ByteString.Output unknownFieldsOutput =
          com.google.protobuf.ByteString.newOutput();
      com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
          com.google.protobuf.CodedOutputStream.newInstance(
              unknownFieldsOutput);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              account_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              password_ = bs;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              com.fise.xiaoyu.protobuf.IMBaseDefine.ClientType value = com.fise.xiaoyu.protobuf.IMBaseDefine.ClientType.valueOf(rawValue);
              if (value == null) {
                unknownFieldsCodedOutput.writeRawVarint32(tag);
                unknownFieldsCodedOutput.writeRawVarint32(rawValue);
              } else {
                bitField0_ |= 0x00000004;
                clientType_ = value;
              }
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              ime_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              province_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              city_ = bs;
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              country_ = bs;
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000080;
              clientVersion_ = bs;
              break;
            }
            case 162: {
              bitField0_ |= 0x00000100;
              attachData_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        try {
          unknownFieldsCodedOutput.flush();
        } catch (java.io.IOException e) {
        // Should not happen
        } finally {
          unknownFields = unknownFieldsOutput.toByteString();
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<IMRegistReq> PARSER =
        new com.google.protobuf.AbstractParser<IMRegistReq>() {
      public IMRegistReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IMRegistReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<IMRegistReq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ACCOUNT_FIELD_NUMBER = 1;
    private java.lang.Object account_;
    /**
     * <code>required string account = 1;</code>
     *
     * <pre>
     *cmd id:	CID_REGIST_REQ_MSGSERVER	0x00ff
     * </pre>
     */
    public boolean hasAccount() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string account = 1;</code>
     *
     * <pre>
     *cmd id:	CID_REGIST_REQ_MSGSERVER	0x00ff
     * </pre>
     */
    public java.lang.String getAccount() {
      java.lang.Object ref = account_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          account_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string account = 1;</code>
     *
     * <pre>
     *cmd id:	CID_REGIST_REQ_MSGSERVER	0x00ff
     * </pre>
     */
    public com.google.protobuf.ByteString
        getAccountBytes() {
      java.lang.Object ref = account_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        account_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 2;
    private java.lang.Object password_;
    /**
     * <code>required string password = 2;</code>
     */
    public boolean hasPassword() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string password = 2;</code>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          password_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string password = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLIENT_TYPE_FIELD_NUMBER = 3;
    private com.fise.xiaoyu.protobuf.IMBaseDefine.ClientType clientType_;
    /**
     * <code>required .IM.BaseDefine.ClientType client_type = 3;</code>
     */
    public boolean hasClientType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required .IM.BaseDefine.ClientType client_type = 3;</code>
     */
    public com.fise.xiaoyu.protobuf.IMBaseDefine.ClientType getClientType() {
      return clientType_;
    }

    public static final int IME_FIELD_NUMBER = 4;
    private java.lang.Object ime_;
    /**
     * <code>required string ime = 4;</code>
     */
    public boolean hasIme() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string ime = 4;</code>
     */
    public java.lang.String getIme() {
      java.lang.Object ref = ime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ime_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string ime = 4;</code>
     */
    public com.google.protobuf.ByteString
        getImeBytes() {
      java.lang.Object ref = ime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROVINCE_FIELD_NUMBER = 5;
    private java.lang.Object province_;
    /**
     * <code>optional string province = 5;</code>
     */
    public boolean hasProvince() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string province = 5;</code>
     */
    public java.lang.String getProvince() {
      java.lang.Object ref = province_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          province_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string province = 5;</code>
     */
    public com.google.protobuf.ByteString
        getProvinceBytes() {
      java.lang.Object ref = province_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        province_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CITY_FIELD_NUMBER = 6;
    private java.lang.Object city_;
    /**
     * <code>optional string city = 6;</code>
     */
    public boolean hasCity() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string city = 6;</code>
     */
    public java.lang.String getCity() {
      java.lang.Object ref = city_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          city_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string city = 6;</code>
     */
    public com.google.protobuf.ByteString
        getCityBytes() {
      java.lang.Object ref = city_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        city_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COUNTRY_FIELD_NUMBER = 7;
    private java.lang.Object country_;
    /**
     * <code>optional string country = 7;</code>
     */
    public boolean hasCountry() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string country = 7;</code>
     */
    public java.lang.String getCountry() {
      java.lang.Object ref = country_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          country_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string country = 7;</code>
     */
    public com.google.protobuf.ByteString
        getCountryBytes() {
      java.lang.Object ref = country_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        country_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLIENT_VERSION_FIELD_NUMBER = 8;
    private java.lang.Object clientVersion_;
    /**
     * <code>optional string client_version = 8;</code>
     */
    public boolean hasClientVersion() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string client_version = 8;</code>
     */
    public java.lang.String getClientVersion() {
      java.lang.Object ref = clientVersion_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          clientVersion_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string client_version = 8;</code>
     */
    public com.google.protobuf.ByteString
        getClientVersionBytes() {
      java.lang.Object ref = clientVersion_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ATTACH_DATA_FIELD_NUMBER = 20;
    private com.google.protobuf.ByteString attachData_;
    /**
     * <code>optional bytes attach_data = 20;</code>
     */
    public boolean hasAttachData() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional bytes attach_data = 20;</code>
     */
    public com.google.protobuf.ByteString getAttachData() {
      return attachData_;
    }

    private void initFields() {
      account_ = "";
      password_ = "";
      clientType_ = com.fise.xiaoyu.protobuf.IMBaseDefine.ClientType.CLIENT_TYPE_WINDOWS;
      ime_ = "";
      province_ = "";
      city_ = "";
      country_ = "";
      clientVersion_ = "";
      attachData_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasAccount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPassword()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasClientType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIme()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getAccountBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPasswordBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, clientType_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getImeBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getProvinceBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getCityBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getCountryBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getClientVersionBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(20, attachData_);
      }
      output.writeRawBytes(unknownFields);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getAccountBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPasswordBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, clientType_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getImeBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getProvinceBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getCityBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getCountryBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getClientVersionBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(20, attachData_);
      }
      size += unknownFields.size();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.fise.xiaoyu.protobuf.IMRegist.IMRegistReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fise.xiaoyu.protobuf.IMRegist.IMRegistReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fise.xiaoyu.protobuf.IMRegist.IMRegistReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fise.xiaoyu.protobuf.IMRegist.IMRegistReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fise.xiaoyu.protobuf.IMRegist.IMRegistReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.fise.xiaoyu.protobuf.IMRegist.IMRegistReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.fise.xiaoyu.protobuf.IMRegist.IMRegistReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.fise.xiaoyu.protobuf.IMRegist.IMRegistReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.fise.xiaoyu.protobuf.IMRegist.IMRegistReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.fise.xiaoyu.protobuf.IMRegist.IMRegistReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.fise.xiaoyu.protobuf.IMRegist.IMRegistReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code IM.Regist.IMRegistReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.fise.xiaoyu.protobuf.IMRegist.IMRegistReq, Builder>
        implements
        // @@protoc_insertion_point(builder_implements:IM.Regist.IMRegistReq)
        com.fise.xiaoyu.protobuf.IMRegist.IMRegistReqOrBuilder {
      // Construct using com.fise.xiaoyu.protobuf.IMRegist.IMRegistReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        account_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        password_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        clientType_ = com.fise.xiaoyu.protobuf.IMBaseDefine.ClientType.CLIENT_TYPE_WINDOWS;
        bitField0_ = (bitField0_ & ~0x00000004);
        ime_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        province_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        city_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        country_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        clientVersion_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        attachData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.fise.xiaoyu.protobuf.IMRegist.IMRegistReq getDefaultInstanceForType() {
        return com.fise.xiaoyu.protobuf.IMRegist.IMRegistReq.getDefaultInstance();
      }

      public com.fise.xiaoyu.protobuf.IMRegist.IMRegistReq build() {
        com.fise.xiaoyu.protobuf.IMRegist.IMRegistReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.fise.xiaoyu.protobuf.IMRegist.IMRegistReq buildPartial() {
        com.fise.xiaoyu.protobuf.IMRegist.IMRegistReq result = new com.fise.xiaoyu.protobuf.IMRegist.IMRegistReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.account_ = account_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.password_ = password_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.clientType_ = clientType_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.ime_ = ime_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.province_ = province_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.city_ = city_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.country_ = country_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.clientVersion_ = clientVersion_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.attachData_ = attachData_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.fise.xiaoyu.protobuf.IMRegist.IMRegistReq other) {
        if (other == com.fise.xiaoyu.protobuf.IMRegist.IMRegistReq.getDefaultInstance()) return this;
        if (other.hasAccount()) {
          bitField0_ |= 0x00000001;
          account_ = other.account_;
          
        }
        if (other.hasPassword()) {
          bitField0_ |= 0x00000002;
          password_ = other.password_;
          
        }
        if (other.hasClientType()) {
          setClientType(other.getClientType());
        }
        if (other.hasIme()) {
          bitField0_ |= 0x00000008;
          ime_ = other.ime_;
          
        }
        if (other.hasProvince()) {
          bitField0_ |= 0x00000010;
          province_ = other.province_;
          
        }
        if (other.hasCity()) {
          bitField0_ |= 0x00000020;
          city_ = other.city_;
          
        }
        if (other.hasCountry()) {
          bitField0_ |= 0x00000040;
          country_ = other.country_;
          
        }
        if (other.hasClientVersion()) {
          bitField0_ |= 0x00000080;
          clientVersion_ = other.clientVersion_;
          
        }
        if (other.hasAttachData()) {
          setAttachData(other.getAttachData());
        }
        setUnknownFields(
            getUnknownFields().concat(other.unknownFields));
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAccount()) {
          
          return false;
        }
        if (!hasPassword()) {
          
          return false;
        }
        if (!hasClientType()) {
          
          return false;
        }
        if (!hasIme()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.fise.xiaoyu.protobuf.IMRegist.IMRegistReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.fise.xiaoyu.protobuf.IMRegist.IMRegistReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object account_ = "";
      /**
       * <code>required string account = 1;</code>
       *
       * <pre>
       *cmd id:	CID_REGIST_REQ_MSGSERVER	0x00ff
       * </pre>
       */
      public boolean hasAccount() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string account = 1;</code>
       *
       * <pre>
       *cmd id:	CID_REGIST_REQ_MSGSERVER	0x00ff
       * </pre>
       */
      public java.lang.String getAccount() {
        java.lang.Object ref = account_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            account_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string account = 1;</code>
       *
       * <pre>
       *cmd id:	CID_REGIST_REQ_MSGSERVER	0x00ff
       * </pre>
       */
      public com.google.protobuf.ByteString
          getAccountBytes() {
        java.lang.Object ref = account_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          account_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string account = 1;</code>
       *
       * <pre>
       *cmd id:	CID_REGIST_REQ_MSGSERVER	0x00ff
       * </pre>
       */
      public Builder setAccount(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        account_ = value;
        
        return this;
      }
      /**
       * <code>required string account = 1;</code>
       *
       * <pre>
       *cmd id:	CID_REGIST_REQ_MSGSERVER	0x00ff
       * </pre>
       */
      public Builder clearAccount() {
        bitField0_ = (bitField0_ & ~0x00000001);
        account_ = getDefaultInstance().getAccount();
        
        return this;
      }
      /**
       * <code>required string account = 1;</code>
       *
       * <pre>
       *cmd id:	CID_REGIST_REQ_MSGSERVER	0x00ff
       * </pre>
       */
      public Builder setAccountBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        account_ = value;
        
        return this;
      }

      private java.lang.Object password_ = "";
      /**
       * <code>required string password = 2;</code>
       */
      public boolean hasPassword() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string password = 2;</code>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            password_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string password = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string password = 2;</code>
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        password_ = value;
        
        return this;
      }
      /**
       * <code>required string password = 2;</code>
       */
      public Builder clearPassword() {
        bitField0_ = (bitField0_ & ~0x00000002);
        password_ = getDefaultInstance().getPassword();
        
        return this;
      }
      /**
       * <code>required string password = 2;</code>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        password_ = value;
        
        return this;
      }

      private com.fise.xiaoyu.protobuf.IMBaseDefine.ClientType clientType_ = com.fise.xiaoyu.protobuf.IMBaseDefine.ClientType.CLIENT_TYPE_WINDOWS;
      /**
       * <code>required .IM.BaseDefine.ClientType client_type = 3;</code>
       */
      public boolean hasClientType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required .IM.BaseDefine.ClientType client_type = 3;</code>
       */
      public com.fise.xiaoyu.protobuf.IMBaseDefine.ClientType getClientType() {
        return clientType_;
      }
      /**
       * <code>required .IM.BaseDefine.ClientType client_type = 3;</code>
       */
      public Builder setClientType(com.fise.xiaoyu.protobuf.IMBaseDefine.ClientType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        clientType_ = value;
        
        return this;
      }
      /**
       * <code>required .IM.BaseDefine.ClientType client_type = 3;</code>
       */
      public Builder clearClientType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        clientType_ = com.fise.xiaoyu.protobuf.IMBaseDefine.ClientType.CLIENT_TYPE_WINDOWS;
        
        return this;
      }

      private java.lang.Object ime_ = "";
      /**
       * <code>required string ime = 4;</code>
       */
      public boolean hasIme() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string ime = 4;</code>
       */
      public java.lang.String getIme() {
        java.lang.Object ref = ime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            ime_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string ime = 4;</code>
       */
      public com.google.protobuf.ByteString
          getImeBytes() {
        java.lang.Object ref = ime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string ime = 4;</code>
       */
      public Builder setIme(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        ime_ = value;
        
        return this;
      }
      /**
       * <code>required string ime = 4;</code>
       */
      public Builder clearIme() {
        bitField0_ = (bitField0_ & ~0x00000008);
        ime_ = getDefaultInstance().getIme();
        
        return this;
      }
      /**
       * <code>required string ime = 4;</code>
       */
      public Builder setImeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        ime_ = value;
        
        return this;
      }

      private java.lang.Object province_ = "";
      /**
       * <code>optional string province = 5;</code>
       */
      public boolean hasProvince() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string province = 5;</code>
       */
      public java.lang.String getProvince() {
        java.lang.Object ref = province_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            province_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string province = 5;</code>
       */
      public com.google.protobuf.ByteString
          getProvinceBytes() {
        java.lang.Object ref = province_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          province_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string province = 5;</code>
       */
      public Builder setProvince(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        province_ = value;
        
        return this;
      }
      /**
       * <code>optional string province = 5;</code>
       */
      public Builder clearProvince() {
        bitField0_ = (bitField0_ & ~0x00000010);
        province_ = getDefaultInstance().getProvince();
        
        return this;
      }
      /**
       * <code>optional string province = 5;</code>
       */
      public Builder setProvinceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        province_ = value;
        
        return this;
      }

      private java.lang.Object city_ = "";
      /**
       * <code>optional string city = 6;</code>
       */
      public boolean hasCity() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string city = 6;</code>
       */
      public java.lang.String getCity() {
        java.lang.Object ref = city_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            city_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string city = 6;</code>
       */
      public com.google.protobuf.ByteString
          getCityBytes() {
        java.lang.Object ref = city_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          city_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string city = 6;</code>
       */
      public Builder setCity(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        city_ = value;
        
        return this;
      }
      /**
       * <code>optional string city = 6;</code>
       */
      public Builder clearCity() {
        bitField0_ = (bitField0_ & ~0x00000020);
        city_ = getDefaultInstance().getCity();
        
        return this;
      }
      /**
       * <code>optional string city = 6;</code>
       */
      public Builder setCityBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        city_ = value;
        
        return this;
      }

      private java.lang.Object country_ = "";
      /**
       * <code>optional string country = 7;</code>
       */
      public boolean hasCountry() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string country = 7;</code>
       */
      public java.lang.String getCountry() {
        java.lang.Object ref = country_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            country_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string country = 7;</code>
       */
      public com.google.protobuf.ByteString
          getCountryBytes() {
        java.lang.Object ref = country_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          country_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string country = 7;</code>
       */
      public Builder setCountry(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        country_ = value;
        
        return this;
      }
      /**
       * <code>optional string country = 7;</code>
       */
      public Builder clearCountry() {
        bitField0_ = (bitField0_ & ~0x00000040);
        country_ = getDefaultInstance().getCountry();
        
        return this;
      }
      /**
       * <code>optional string country = 7;</code>
       */
      public Builder setCountryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        country_ = value;
        
        return this;
      }

      private java.lang.Object clientVersion_ = "";
      /**
       * <code>optional string client_version = 8;</code>
       */
      public boolean hasClientVersion() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string client_version = 8;</code>
       */
      public java.lang.String getClientVersion() {
        java.lang.Object ref = clientVersion_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            clientVersion_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string client_version = 8;</code>
       */
      public com.google.protobuf.ByteString
          getClientVersionBytes() {
        java.lang.Object ref = clientVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string client_version = 8;</code>
       */
      public Builder setClientVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        clientVersion_ = value;
        
        return this;
      }
      /**
       * <code>optional string client_version = 8;</code>
       */
      public Builder clearClientVersion() {
        bitField0_ = (bitField0_ & ~0x00000080);
        clientVersion_ = getDefaultInstance().getClientVersion();
        
        return this;
      }
      /**
       * <code>optional string client_version = 8;</code>
       */
      public Builder setClientVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        clientVersion_ = value;
        
        return this;
      }

      private com.google.protobuf.ByteString attachData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes attach_data = 20;</code>
       */
      public boolean hasAttachData() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional bytes attach_data = 20;</code>
       */
      public com.google.protobuf.ByteString getAttachData() {
        return attachData_;
      }
      /**
       * <code>optional bytes attach_data = 20;</code>
       */
      public Builder setAttachData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        attachData_ = value;
        
        return this;
      }
      /**
       * <code>optional bytes attach_data = 20;</code>
       */
      public Builder clearAttachData() {
        bitField0_ = (bitField0_ & ~0x00000100);
        attachData_ = getDefaultInstance().getAttachData();
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:IM.Regist.IMRegistReq)
    }

    static {
      defaultInstance = new IMRegistReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:IM.Regist.IMRegistReq)
  }

  public interface IMRegistResOrBuilder extends
      // @@protoc_insertion_point(interface_extends:IM.Regist.IMRegistRes)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required uint32 server_time = 1;</code>
     *
     * <pre>
     *cmd id:	CID_REGIST_RES_MSGSERVER	0x0100
     * </pre>
     */
    boolean hasServerTime();
    /**
     * <code>required uint32 server_time = 1;</code>
     *
     * <pre>
     *cmd id:	CID_REGIST_RES_MSGSERVER	0x0100
     * </pre>
     */
    int getServerTime();

    /**
     * <code>required .IM.BaseDefine.ResultType result_code = 2;</code>
     */
    boolean hasResultCode();
    /**
     * <code>required .IM.BaseDefine.ResultType result_code = 2;</code>
     */
    com.fise.xiaoyu.protobuf.IMBaseDefine.ResultType getResultCode();

    /**
     * <code>optional string result_string = 3;</code>
     */
    boolean hasResultString();
    /**
     * <code>optional string result_string = 3;</code>
     */
    java.lang.String getResultString();
    /**
     * <code>optional string result_string = 3;</code>
     */
    com.google.protobuf.ByteString
        getResultStringBytes();

    /**
     * <code>optional .IM.BaseDefine.UserStatType online_status = 4;</code>
     */
    boolean hasOnlineStatus();
    /**
     * <code>optional .IM.BaseDefine.UserStatType online_status = 4;</code>
     */
    com.fise.xiaoyu.protobuf.IMBaseDefine.UserStatType getOnlineStatus();

    /**
     * <code>optional .IM.BaseDefine.UserInfo user_info = 5;</code>
     */
    boolean hasUserInfo();
    /**
     * <code>optional .IM.BaseDefine.UserInfo user_info = 5;</code>
     */
    com.fise.xiaoyu.protobuf.IMBaseDefine.UserInfo getUserInfo();

    /**
     * <code>optional string account = 6;</code>
     */
    boolean hasAccount();
    /**
     * <code>optional string account = 6;</code>
     */
    java.lang.String getAccount();
    /**
     * <code>optional string account = 6;</code>
     */
    com.google.protobuf.ByteString
        getAccountBytes();

    /**
     * <code>optional string login_token = 7;</code>
     */
    boolean hasLoginToken();
    /**
     * <code>optional string login_token = 7;</code>
     */
    java.lang.String getLoginToken();
    /**
     * <code>optional string login_token = 7;</code>
     */
    com.google.protobuf.ByteString
        getLoginTokenBytes();

    /**
     * <code>optional bytes attach_data = 20;</code>
     */
    boolean hasAttachData();
    /**
     * <code>optional bytes attach_data = 20;</code>
     */
    com.google.protobuf.ByteString getAttachData();
  }
  /**
   * Protobuf type {@code IM.Regist.IMRegistRes}
   */
  public static final class IMRegistRes extends
      com.google.protobuf.GeneratedMessageLite implements
      // @@protoc_insertion_point(message_implements:IM.Regist.IMRegistRes)
      IMRegistResOrBuilder {
    // Use IMRegistRes.newBuilder() to construct.
    private IMRegistRes(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private IMRegistRes(boolean noInit) { this.unknownFields = com.google.protobuf.ByteString.EMPTY;}

    private static final IMRegistRes defaultInstance;
    public static IMRegistRes getDefaultInstance() {
      return defaultInstance;
    }

    public IMRegistRes getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.ByteString unknownFields;
    private IMRegistRes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.ByteString.Output unknownFieldsOutput =
          com.google.protobuf.ByteString.newOutput();
      com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
          com.google.protobuf.CodedOutputStream.newInstance(
              unknownFieldsOutput);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              serverTime_ = input.readUInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.fise.xiaoyu.protobuf.IMBaseDefine.ResultType value = com.fise.xiaoyu.protobuf.IMBaseDefine.ResultType.valueOf(rawValue);
              if (value == null) {
                unknownFieldsCodedOutput.writeRawVarint32(tag);
                unknownFieldsCodedOutput.writeRawVarint32(rawValue);
              } else {
                bitField0_ |= 0x00000002;
                resultCode_ = value;
              }
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              resultString_ = bs;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              com.fise.xiaoyu.protobuf.IMBaseDefine.UserStatType value = com.fise.xiaoyu.protobuf.IMBaseDefine.UserStatType.valueOf(rawValue);
              if (value == null) {
                unknownFieldsCodedOutput.writeRawVarint32(tag);
                unknownFieldsCodedOutput.writeRawVarint32(rawValue);
              } else {
                bitField0_ |= 0x00000008;
                onlineStatus_ = value;
              }
              break;
            }
            case 42: {
              com.fise.xiaoyu.protobuf.IMBaseDefine.UserInfo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000010) == 0x00000010)) {
                subBuilder = userInfo_.toBuilder();
              }
              userInfo_ = input.readMessage(com.fise.xiaoyu.protobuf.IMBaseDefine.UserInfo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(userInfo_);
                userInfo_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000010;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              account_ = bs;
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              loginToken_ = bs;
              break;
            }
            case 162: {
              bitField0_ |= 0x00000080;
              attachData_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        try {
          unknownFieldsCodedOutput.flush();
        } catch (java.io.IOException e) {
        // Should not happen
        } finally {
          unknownFields = unknownFieldsOutput.toByteString();
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<IMRegistRes> PARSER =
        new com.google.protobuf.AbstractParser<IMRegistRes>() {
      public IMRegistRes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IMRegistRes(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<IMRegistRes> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SERVER_TIME_FIELD_NUMBER = 1;
    private int serverTime_;
    /**
     * <code>required uint32 server_time = 1;</code>
     *
     * <pre>
     *cmd id:	CID_REGIST_RES_MSGSERVER	0x0100
     * </pre>
     */
    public boolean hasServerTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 server_time = 1;</code>
     *
     * <pre>
     *cmd id:	CID_REGIST_RES_MSGSERVER	0x0100
     * </pre>
     */
    public int getServerTime() {
      return serverTime_;
    }

    public static final int RESULT_CODE_FIELD_NUMBER = 2;
    private com.fise.xiaoyu.protobuf.IMBaseDefine.ResultType resultCode_;
    /**
     * <code>required .IM.BaseDefine.ResultType result_code = 2;</code>
     */
    public boolean hasResultCode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .IM.BaseDefine.ResultType result_code = 2;</code>
     */
    public com.fise.xiaoyu.protobuf.IMBaseDefine.ResultType getResultCode() {
      return resultCode_;
    }

    public static final int RESULT_STRING_FIELD_NUMBER = 3;
    private java.lang.Object resultString_;
    /**
     * <code>optional string result_string = 3;</code>
     */
    public boolean hasResultString() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string result_string = 3;</code>
     */
    public java.lang.String getResultString() {
      java.lang.Object ref = resultString_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          resultString_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string result_string = 3;</code>
     */
    public com.google.protobuf.ByteString
        getResultStringBytes() {
      java.lang.Object ref = resultString_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resultString_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ONLINE_STATUS_FIELD_NUMBER = 4;
    private com.fise.xiaoyu.protobuf.IMBaseDefine.UserStatType onlineStatus_;
    /**
     * <code>optional .IM.BaseDefine.UserStatType online_status = 4;</code>
     */
    public boolean hasOnlineStatus() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .IM.BaseDefine.UserStatType online_status = 4;</code>
     */
    public com.fise.xiaoyu.protobuf.IMBaseDefine.UserStatType getOnlineStatus() {
      return onlineStatus_;
    }

    public static final int USER_INFO_FIELD_NUMBER = 5;
    private com.fise.xiaoyu.protobuf.IMBaseDefine.UserInfo userInfo_;
    /**
     * <code>optional .IM.BaseDefine.UserInfo user_info = 5;</code>
     */
    public boolean hasUserInfo() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .IM.BaseDefine.UserInfo user_info = 5;</code>
     */
    public com.fise.xiaoyu.protobuf.IMBaseDefine.UserInfo getUserInfo() {
      return userInfo_;
    }

    public static final int ACCOUNT_FIELD_NUMBER = 6;
    private java.lang.Object account_;
    /**
     * <code>optional string account = 6;</code>
     */
    public boolean hasAccount() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string account = 6;</code>
     */
    public java.lang.String getAccount() {
      java.lang.Object ref = account_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          account_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string account = 6;</code>
     */
    public com.google.protobuf.ByteString
        getAccountBytes() {
      java.lang.Object ref = account_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        account_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOGIN_TOKEN_FIELD_NUMBER = 7;
    private java.lang.Object loginToken_;
    /**
     * <code>optional string login_token = 7;</code>
     */
    public boolean hasLoginToken() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string login_token = 7;</code>
     */
    public java.lang.String getLoginToken() {
      java.lang.Object ref = loginToken_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          loginToken_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string login_token = 7;</code>
     */
    public com.google.protobuf.ByteString
        getLoginTokenBytes() {
      java.lang.Object ref = loginToken_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        loginToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ATTACH_DATA_FIELD_NUMBER = 20;
    private com.google.protobuf.ByteString attachData_;
    /**
     * <code>optional bytes attach_data = 20;</code>
     */
    public boolean hasAttachData() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional bytes attach_data = 20;</code>
     */
    public com.google.protobuf.ByteString getAttachData() {
      return attachData_;
    }

    private void initFields() {
      serverTime_ = 0;
      resultCode_ = com.fise.xiaoyu.protobuf.IMBaseDefine.ResultType.REFUSE_REASON_NONE;
      resultString_ = "";
      onlineStatus_ = com.fise.xiaoyu.protobuf.IMBaseDefine.UserStatType.USER_STATUS_INIT;
      userInfo_ = com.fise.xiaoyu.protobuf.IMBaseDefine.UserInfo.getDefaultInstance();
      account_ = "";
      loginToken_ = "";
      attachData_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasServerTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasResultCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasUserInfo()) {
        if (!getUserInfo().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, serverTime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, resultCode_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getResultStringBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeEnum(4, onlineStatus_.getNumber());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(5, userInfo_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getAccountBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getLoginTokenBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(20, attachData_);
      }
      output.writeRawBytes(unknownFields);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, serverTime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, resultCode_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getResultStringBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, onlineStatus_.getNumber());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, userInfo_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getAccountBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getLoginTokenBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(20, attachData_);
      }
      size += unknownFields.size();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.fise.xiaoyu.protobuf.IMRegist.IMRegistRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fise.xiaoyu.protobuf.IMRegist.IMRegistRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fise.xiaoyu.protobuf.IMRegist.IMRegistRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fise.xiaoyu.protobuf.IMRegist.IMRegistRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fise.xiaoyu.protobuf.IMRegist.IMRegistRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.fise.xiaoyu.protobuf.IMRegist.IMRegistRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.fise.xiaoyu.protobuf.IMRegist.IMRegistRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.fise.xiaoyu.protobuf.IMRegist.IMRegistRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.fise.xiaoyu.protobuf.IMRegist.IMRegistRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.fise.xiaoyu.protobuf.IMRegist.IMRegistRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.fise.xiaoyu.protobuf.IMRegist.IMRegistRes prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code IM.Regist.IMRegistRes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.fise.xiaoyu.protobuf.IMRegist.IMRegistRes, Builder>
        implements
        // @@protoc_insertion_point(builder_implements:IM.Regist.IMRegistRes)
        com.fise.xiaoyu.protobuf.IMRegist.IMRegistResOrBuilder {
      // Construct using com.fise.xiaoyu.protobuf.IMRegist.IMRegistRes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        serverTime_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        resultCode_ = com.fise.xiaoyu.protobuf.IMBaseDefine.ResultType.REFUSE_REASON_NONE;
        bitField0_ = (bitField0_ & ~0x00000002);
        resultString_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        onlineStatus_ = com.fise.xiaoyu.protobuf.IMBaseDefine.UserStatType.USER_STATUS_INIT;
        bitField0_ = (bitField0_ & ~0x00000008);
        userInfo_ = com.fise.xiaoyu.protobuf.IMBaseDefine.UserInfo.getDefaultInstance();
        bitField0_ = (bitField0_ & ~0x00000010);
        account_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        loginToken_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        attachData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.fise.xiaoyu.protobuf.IMRegist.IMRegistRes getDefaultInstanceForType() {
        return com.fise.xiaoyu.protobuf.IMRegist.IMRegistRes.getDefaultInstance();
      }

      public com.fise.xiaoyu.protobuf.IMRegist.IMRegistRes build() {
        com.fise.xiaoyu.protobuf.IMRegist.IMRegistRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.fise.xiaoyu.protobuf.IMRegist.IMRegistRes buildPartial() {
        com.fise.xiaoyu.protobuf.IMRegist.IMRegistRes result = new com.fise.xiaoyu.protobuf.IMRegist.IMRegistRes(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.serverTime_ = serverTime_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.resultCode_ = resultCode_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.resultString_ = resultString_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.onlineStatus_ = onlineStatus_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.userInfo_ = userInfo_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.account_ = account_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.loginToken_ = loginToken_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.attachData_ = attachData_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.fise.xiaoyu.protobuf.IMRegist.IMRegistRes other) {
        if (other == com.fise.xiaoyu.protobuf.IMRegist.IMRegistRes.getDefaultInstance()) return this;
        if (other.hasServerTime()) {
          setServerTime(other.getServerTime());
        }
        if (other.hasResultCode()) {
          setResultCode(other.getResultCode());
        }
        if (other.hasResultString()) {
          bitField0_ |= 0x00000004;
          resultString_ = other.resultString_;
          
        }
        if (other.hasOnlineStatus()) {
          setOnlineStatus(other.getOnlineStatus());
        }
        if (other.hasUserInfo()) {
          mergeUserInfo(other.getUserInfo());
        }
        if (other.hasAccount()) {
          bitField0_ |= 0x00000020;
          account_ = other.account_;
          
        }
        if (other.hasLoginToken()) {
          bitField0_ |= 0x00000040;
          loginToken_ = other.loginToken_;
          
        }
        if (other.hasAttachData()) {
          setAttachData(other.getAttachData());
        }
        setUnknownFields(
            getUnknownFields().concat(other.unknownFields));
        return this;
      }

      public final boolean isInitialized() {
        if (!hasServerTime()) {
          
          return false;
        }
        if (!hasResultCode()) {
          
          return false;
        }
        if (hasUserInfo()) {
          if (!getUserInfo().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.fise.xiaoyu.protobuf.IMRegist.IMRegistRes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.fise.xiaoyu.protobuf.IMRegist.IMRegistRes) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int serverTime_ ;
      /**
       * <code>required uint32 server_time = 1;</code>
       *
       * <pre>
       *cmd id:	CID_REGIST_RES_MSGSERVER	0x0100
       * </pre>
       */
      public boolean hasServerTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 server_time = 1;</code>
       *
       * <pre>
       *cmd id:	CID_REGIST_RES_MSGSERVER	0x0100
       * </pre>
       */
      public int getServerTime() {
        return serverTime_;
      }
      /**
       * <code>required uint32 server_time = 1;</code>
       *
       * <pre>
       *cmd id:	CID_REGIST_RES_MSGSERVER	0x0100
       * </pre>
       */
      public Builder setServerTime(int value) {
        bitField0_ |= 0x00000001;
        serverTime_ = value;
        
        return this;
      }
      /**
       * <code>required uint32 server_time = 1;</code>
       *
       * <pre>
       *cmd id:	CID_REGIST_RES_MSGSERVER	0x0100
       * </pre>
       */
      public Builder clearServerTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serverTime_ = 0;
        
        return this;
      }

      private com.fise.xiaoyu.protobuf.IMBaseDefine.ResultType resultCode_ = com.fise.xiaoyu.protobuf.IMBaseDefine.ResultType.REFUSE_REASON_NONE;
      /**
       * <code>required .IM.BaseDefine.ResultType result_code = 2;</code>
       */
      public boolean hasResultCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .IM.BaseDefine.ResultType result_code = 2;</code>
       */
      public com.fise.xiaoyu.protobuf.IMBaseDefine.ResultType getResultCode() {
        return resultCode_;
      }
      /**
       * <code>required .IM.BaseDefine.ResultType result_code = 2;</code>
       */
      public Builder setResultCode(com.fise.xiaoyu.protobuf.IMBaseDefine.ResultType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        resultCode_ = value;
        
        return this;
      }
      /**
       * <code>required .IM.BaseDefine.ResultType result_code = 2;</code>
       */
      public Builder clearResultCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        resultCode_ = com.fise.xiaoyu.protobuf.IMBaseDefine.ResultType.REFUSE_REASON_NONE;
        
        return this;
      }

      private java.lang.Object resultString_ = "";
      /**
       * <code>optional string result_string = 3;</code>
       */
      public boolean hasResultString() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string result_string = 3;</code>
       */
      public java.lang.String getResultString() {
        java.lang.Object ref = resultString_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            resultString_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string result_string = 3;</code>
       */
      public com.google.protobuf.ByteString
          getResultStringBytes() {
        java.lang.Object ref = resultString_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          resultString_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string result_string = 3;</code>
       */
      public Builder setResultString(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        resultString_ = value;
        
        return this;
      }
      /**
       * <code>optional string result_string = 3;</code>
       */
      public Builder clearResultString() {
        bitField0_ = (bitField0_ & ~0x00000004);
        resultString_ = getDefaultInstance().getResultString();
        
        return this;
      }
      /**
       * <code>optional string result_string = 3;</code>
       */
      public Builder setResultStringBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        resultString_ = value;
        
        return this;
      }

      private com.fise.xiaoyu.protobuf.IMBaseDefine.UserStatType onlineStatus_ = com.fise.xiaoyu.protobuf.IMBaseDefine.UserStatType.USER_STATUS_INIT;
      /**
       * <code>optional .IM.BaseDefine.UserStatType online_status = 4;</code>
       */
      public boolean hasOnlineStatus() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .IM.BaseDefine.UserStatType online_status = 4;</code>
       */
      public com.fise.xiaoyu.protobuf.IMBaseDefine.UserStatType getOnlineStatus() {
        return onlineStatus_;
      }
      /**
       * <code>optional .IM.BaseDefine.UserStatType online_status = 4;</code>
       */
      public Builder setOnlineStatus(com.fise.xiaoyu.protobuf.IMBaseDefine.UserStatType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        onlineStatus_ = value;
        
        return this;
      }
      /**
       * <code>optional .IM.BaseDefine.UserStatType online_status = 4;</code>
       */
      public Builder clearOnlineStatus() {
        bitField0_ = (bitField0_ & ~0x00000008);
        onlineStatus_ = com.fise.xiaoyu.protobuf.IMBaseDefine.UserStatType.USER_STATUS_INIT;
        
        return this;
      }

      private com.fise.xiaoyu.protobuf.IMBaseDefine.UserInfo userInfo_ = com.fise.xiaoyu.protobuf.IMBaseDefine.UserInfo.getDefaultInstance();
      /**
       * <code>optional .IM.BaseDefine.UserInfo user_info = 5;</code>
       */
      public boolean hasUserInfo() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .IM.BaseDefine.UserInfo user_info = 5;</code>
       */
      public com.fise.xiaoyu.protobuf.IMBaseDefine.UserInfo getUserInfo() {
        return userInfo_;
      }
      /**
       * <code>optional .IM.BaseDefine.UserInfo user_info = 5;</code>
       */
      public Builder setUserInfo(com.fise.xiaoyu.protobuf.IMBaseDefine.UserInfo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        userInfo_ = value;

        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .IM.BaseDefine.UserInfo user_info = 5;</code>
       */
      public Builder setUserInfo(
          com.fise.xiaoyu.protobuf.IMBaseDefine.UserInfo.Builder builderForValue) {
        userInfo_ = builderForValue.build();

        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .IM.BaseDefine.UserInfo user_info = 5;</code>
       */
      public Builder mergeUserInfo(com.fise.xiaoyu.protobuf.IMBaseDefine.UserInfo value) {
        if (((bitField0_ & 0x00000010) == 0x00000010) &&
            userInfo_ != com.fise.xiaoyu.protobuf.IMBaseDefine.UserInfo.getDefaultInstance()) {
          userInfo_ =
            com.fise.xiaoyu.protobuf.IMBaseDefine.UserInfo.newBuilder(userInfo_).mergeFrom(value).buildPartial();
        } else {
          userInfo_ = value;
        }

        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .IM.BaseDefine.UserInfo user_info = 5;</code>
       */
      public Builder clearUserInfo() {
        userInfo_ = com.fise.xiaoyu.protobuf.IMBaseDefine.UserInfo.getDefaultInstance();

        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      private java.lang.Object account_ = "";
      /**
       * <code>optional string account = 6;</code>
       */
      public boolean hasAccount() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string account = 6;</code>
       */
      public java.lang.String getAccount() {
        java.lang.Object ref = account_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            account_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string account = 6;</code>
       */
      public com.google.protobuf.ByteString
          getAccountBytes() {
        java.lang.Object ref = account_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          account_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string account = 6;</code>
       */
      public Builder setAccount(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        account_ = value;
        
        return this;
      }
      /**
       * <code>optional string account = 6;</code>
       */
      public Builder clearAccount() {
        bitField0_ = (bitField0_ & ~0x00000020);
        account_ = getDefaultInstance().getAccount();
        
        return this;
      }
      /**
       * <code>optional string account = 6;</code>
       */
      public Builder setAccountBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        account_ = value;
        
        return this;
      }

      private java.lang.Object loginToken_ = "";
      /**
       * <code>optional string login_token = 7;</code>
       */
      public boolean hasLoginToken() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string login_token = 7;</code>
       */
      public java.lang.String getLoginToken() {
        java.lang.Object ref = loginToken_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            loginToken_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string login_token = 7;</code>
       */
      public com.google.protobuf.ByteString
          getLoginTokenBytes() {
        java.lang.Object ref = loginToken_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          loginToken_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string login_token = 7;</code>
       */
      public Builder setLoginToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        loginToken_ = value;
        
        return this;
      }
      /**
       * <code>optional string login_token = 7;</code>
       */
      public Builder clearLoginToken() {
        bitField0_ = (bitField0_ & ~0x00000040);
        loginToken_ = getDefaultInstance().getLoginToken();
        
        return this;
      }
      /**
       * <code>optional string login_token = 7;</code>
       */
      public Builder setLoginTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        loginToken_ = value;
        
        return this;
      }

      private com.google.protobuf.ByteString attachData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes attach_data = 20;</code>
       */
      public boolean hasAttachData() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional bytes attach_data = 20;</code>
       */
      public com.google.protobuf.ByteString getAttachData() {
        return attachData_;
      }
      /**
       * <code>optional bytes attach_data = 20;</code>
       */
      public Builder setAttachData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        attachData_ = value;
        
        return this;
      }
      /**
       * <code>optional bytes attach_data = 20;</code>
       */
      public Builder clearAttachData() {
        bitField0_ = (bitField0_ & ~0x00000080);
        attachData_ = getDefaultInstance().getAttachData();
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:IM.Regist.IMRegistRes)
    }

    static {
      defaultInstance = new IMRegistRes(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:IM.Regist.IMRegistRes)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
