// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IM.Sms.proto

package com.fise.xw.protobuf;

public final class IMSms {
  private IMSms() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code IM.Sms.SmsActionType}
   */
  public enum SmsActionType
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>SMS_ACTION_REGIST = 0;</code>
     */
    SMS_ACTION_REGIST(0, 0),
    /**
     * <code>SMS_ACTION_AUTH_DEVICE = 1;</code>
     */
    SMS_ACTION_AUTH_DEVICE(1, 1),
    /**
     * <code>SMS_ACTION_RESET_PASSWORD = 2;</code>
     */
    SMS_ACTION_RESET_PASSWORD(2, 2),
    /**
     * <code>SMS_ACTION_FORGET_PASSWORD = 3;</code>
     */
    SMS_ACTION_FORGET_PASSWORD(3, 3),
    ;

    /**
     * <code>SMS_ACTION_REGIST = 0;</code>
     */
    public static final int SMS_ACTION_REGIST_VALUE = 0;
    /**
     * <code>SMS_ACTION_AUTH_DEVICE = 1;</code>
     */
    public static final int SMS_ACTION_AUTH_DEVICE_VALUE = 1;
    /**
     * <code>SMS_ACTION_RESET_PASSWORD = 2;</code>
     */
    public static final int SMS_ACTION_RESET_PASSWORD_VALUE = 2;
    /**
     * <code>SMS_ACTION_FORGET_PASSWORD = 3;</code>
     */
    public static final int SMS_ACTION_FORGET_PASSWORD_VALUE = 3;


    public final int getNumber() { return value; }

    public static SmsActionType valueOf(int value) {
      switch (value) {
        case 0: return SMS_ACTION_REGIST;
        case 1: return SMS_ACTION_AUTH_DEVICE;
        case 2: return SMS_ACTION_RESET_PASSWORD;
        case 3: return SMS_ACTION_FORGET_PASSWORD;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<SmsActionType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<SmsActionType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<SmsActionType>() {
            public SmsActionType findValueByNumber(int number) {
              return SmsActionType.valueOf(number);
            }
          };

    private final int value;

    private SmsActionType(int index, int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:IM.Sms.SmsActionType)
  }

  public interface IMSendSmsReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:IM.Sms.IMSendSmsReq)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required string mobile = 1;</code>
     *
     * <pre>
     *cmd id:	CID_SMS_SEND_REQUEST  = 0x1000
     * </pre>
     */
    boolean hasMobile();
    /**
     * <code>required string mobile = 1;</code>
     *
     * <pre>
     *cmd id:	CID_SMS_SEND_REQUEST  = 0x1000
     * </pre>
     */
    java.lang.String getMobile();
    /**
     * <code>required string mobile = 1;</code>
     *
     * <pre>
     *cmd id:	CID_SMS_SEND_REQUEST  = 0x1000
     * </pre>
     */
    com.google.protobuf.ByteString
        getMobileBytes();

    /**
     * <code>required .IM.Sms.SmsActionType action = 2;</code>
     */
    boolean hasAction();
    /**
     * <code>required .IM.Sms.SmsActionType action = 2;</code>
     */
    com.fise.xw.protobuf.IMSms.SmsActionType getAction();

    /**
     * <code>optional string param = 3;</code>
     */
    boolean hasParam();
    /**
     * <code>optional string param = 3;</code>
     */
    java.lang.String getParam();
    /**
     * <code>optional string param = 3;</code>
     */
    com.google.protobuf.ByteString
        getParamBytes();

    /**
     * <code>optional bytes attach_data = 20;</code>
     */
    boolean hasAttachData();
    /**
     * <code>optional bytes attach_data = 20;</code>
     */
    com.google.protobuf.ByteString getAttachData();
  }
  /**
   * Protobuf type {@code IM.Sms.IMSendSmsReq}
   */
  public static final class IMSendSmsReq extends
      com.google.protobuf.GeneratedMessageLite implements
      // @@protoc_insertion_point(message_implements:IM.Sms.IMSendSmsReq)
      IMSendSmsReqOrBuilder {
    // Use IMSendSmsReq.newBuilder() to construct.
    private IMSendSmsReq(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private IMSendSmsReq(boolean noInit) { this.unknownFields = com.google.protobuf.ByteString.EMPTY;}

    private static final IMSendSmsReq defaultInstance;
    public static IMSendSmsReq getDefaultInstance() {
      return defaultInstance;
    }

    public IMSendSmsReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.ByteString unknownFields;
    private IMSendSmsReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.ByteString.Output unknownFieldsOutput =
          com.google.protobuf.ByteString.newOutput();
      com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
          com.google.protobuf.CodedOutputStream.newInstance(
              unknownFieldsOutput);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              mobile_ = bs;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.fise.xw.protobuf.IMSms.SmsActionType value = com.fise.xw.protobuf.IMSms.SmsActionType.valueOf(rawValue);
              if (value == null) {
                unknownFieldsCodedOutput.writeRawVarint32(tag);
                unknownFieldsCodedOutput.writeRawVarint32(rawValue);
              } else {
                bitField0_ |= 0x00000002;
                action_ = value;
              }
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              param_ = bs;
              break;
            }
            case 162: {
              bitField0_ |= 0x00000008;
              attachData_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        try {
          unknownFieldsCodedOutput.flush();
        } catch (java.io.IOException e) {
        // Should not happen
        } finally {
          unknownFields = unknownFieldsOutput.toByteString();
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<IMSendSmsReq> PARSER =
        new com.google.protobuf.AbstractParser<IMSendSmsReq>() {
      public IMSendSmsReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IMSendSmsReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<IMSendSmsReq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int MOBILE_FIELD_NUMBER = 1;
    private java.lang.Object mobile_;
    /**
     * <code>required string mobile = 1;</code>
     *
     * <pre>
     *cmd id:	CID_SMS_SEND_REQUEST  = 0x1000
     * </pre>
     */
    public boolean hasMobile() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string mobile = 1;</code>
     *
     * <pre>
     *cmd id:	CID_SMS_SEND_REQUEST  = 0x1000
     * </pre>
     */
    public java.lang.String getMobile() {
      java.lang.Object ref = mobile_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          mobile_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string mobile = 1;</code>
     *
     * <pre>
     *cmd id:	CID_SMS_SEND_REQUEST  = 0x1000
     * </pre>
     */
    public com.google.protobuf.ByteString
        getMobileBytes() {
      java.lang.Object ref = mobile_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mobile_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACTION_FIELD_NUMBER = 2;
    private com.fise.xw.protobuf.IMSms.SmsActionType action_;
    /**
     * <code>required .IM.Sms.SmsActionType action = 2;</code>
     */
    public boolean hasAction() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .IM.Sms.SmsActionType action = 2;</code>
     */
    public com.fise.xw.protobuf.IMSms.SmsActionType getAction() {
      return action_;
    }

    public static final int PARAM_FIELD_NUMBER = 3;
    private java.lang.Object param_;
    /**
     * <code>optional string param = 3;</code>
     */
    public boolean hasParam() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string param = 3;</code>
     */
    public java.lang.String getParam() {
      java.lang.Object ref = param_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          param_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string param = 3;</code>
     */
    public com.google.protobuf.ByteString
        getParamBytes() {
      java.lang.Object ref = param_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        param_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ATTACH_DATA_FIELD_NUMBER = 20;
    private com.google.protobuf.ByteString attachData_;
    /**
     * <code>optional bytes attach_data = 20;</code>
     */
    public boolean hasAttachData() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bytes attach_data = 20;</code>
     */
    public com.google.protobuf.ByteString getAttachData() {
      return attachData_;
    }

    private void initFields() {
      mobile_ = "";
      action_ = com.fise.xw.protobuf.IMSms.SmsActionType.SMS_ACTION_REGIST;
      param_ = "";
      attachData_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMobile()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAction()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getMobileBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, action_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getParamBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(20, attachData_);
      }
      output.writeRawBytes(unknownFields);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getMobileBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, action_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getParamBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(20, attachData_);
      }
      size += unknownFields.size();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.fise.xw.protobuf.IMSms.IMSendSmsReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fise.xw.protobuf.IMSms.IMSendSmsReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fise.xw.protobuf.IMSms.IMSendSmsReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fise.xw.protobuf.IMSms.IMSendSmsReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fise.xw.protobuf.IMSms.IMSendSmsReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.fise.xw.protobuf.IMSms.IMSendSmsReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.fise.xw.protobuf.IMSms.IMSendSmsReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.fise.xw.protobuf.IMSms.IMSendSmsReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.fise.xw.protobuf.IMSms.IMSendSmsReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.fise.xw.protobuf.IMSms.IMSendSmsReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.fise.xw.protobuf.IMSms.IMSendSmsReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code IM.Sms.IMSendSmsReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.fise.xw.protobuf.IMSms.IMSendSmsReq, Builder>
        implements
        // @@protoc_insertion_point(builder_implements:IM.Sms.IMSendSmsReq)
        com.fise.xw.protobuf.IMSms.IMSendSmsReqOrBuilder {
      // Construct using com.fise.xw.protobuf.IMSms.IMSendSmsReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        mobile_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        action_ = com.fise.xw.protobuf.IMSms.SmsActionType.SMS_ACTION_REGIST;
        bitField0_ = (bitField0_ & ~0x00000002);
        param_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        attachData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.fise.xw.protobuf.IMSms.IMSendSmsReq getDefaultInstanceForType() {
        return com.fise.xw.protobuf.IMSms.IMSendSmsReq.getDefaultInstance();
      }

      public com.fise.xw.protobuf.IMSms.IMSendSmsReq build() {
        com.fise.xw.protobuf.IMSms.IMSendSmsReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.fise.xw.protobuf.IMSms.IMSendSmsReq buildPartial() {
        com.fise.xw.protobuf.IMSms.IMSendSmsReq result = new com.fise.xw.protobuf.IMSms.IMSendSmsReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.mobile_ = mobile_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.action_ = action_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.param_ = param_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.attachData_ = attachData_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.fise.xw.protobuf.IMSms.IMSendSmsReq other) {
        if (other == com.fise.xw.protobuf.IMSms.IMSendSmsReq.getDefaultInstance()) return this;
        if (other.hasMobile()) {
          bitField0_ |= 0x00000001;
          mobile_ = other.mobile_;
          
        }
        if (other.hasAction()) {
          setAction(other.getAction());
        }
        if (other.hasParam()) {
          bitField0_ |= 0x00000004;
          param_ = other.param_;
          
        }
        if (other.hasAttachData()) {
          setAttachData(other.getAttachData());
        }
        setUnknownFields(
            getUnknownFields().concat(other.unknownFields));
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMobile()) {
          
          return false;
        }
        if (!hasAction()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.fise.xw.protobuf.IMSms.IMSendSmsReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.fise.xw.protobuf.IMSms.IMSendSmsReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object mobile_ = "";
      /**
       * <code>required string mobile = 1;</code>
       *
       * <pre>
       *cmd id:	CID_SMS_SEND_REQUEST  = 0x1000
       * </pre>
       */
      public boolean hasMobile() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string mobile = 1;</code>
       *
       * <pre>
       *cmd id:	CID_SMS_SEND_REQUEST  = 0x1000
       * </pre>
       */
      public java.lang.String getMobile() {
        java.lang.Object ref = mobile_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            mobile_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string mobile = 1;</code>
       *
       * <pre>
       *cmd id:	CID_SMS_SEND_REQUEST  = 0x1000
       * </pre>
       */
      public com.google.protobuf.ByteString
          getMobileBytes() {
        java.lang.Object ref = mobile_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mobile_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string mobile = 1;</code>
       *
       * <pre>
       *cmd id:	CID_SMS_SEND_REQUEST  = 0x1000
       * </pre>
       */
      public Builder setMobile(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        mobile_ = value;
        
        return this;
      }
      /**
       * <code>required string mobile = 1;</code>
       *
       * <pre>
       *cmd id:	CID_SMS_SEND_REQUEST  = 0x1000
       * </pre>
       */
      public Builder clearMobile() {
        bitField0_ = (bitField0_ & ~0x00000001);
        mobile_ = getDefaultInstance().getMobile();
        
        return this;
      }
      /**
       * <code>required string mobile = 1;</code>
       *
       * <pre>
       *cmd id:	CID_SMS_SEND_REQUEST  = 0x1000
       * </pre>
       */
      public Builder setMobileBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        mobile_ = value;
        
        return this;
      }

      private com.fise.xw.protobuf.IMSms.SmsActionType action_ = com.fise.xw.protobuf.IMSms.SmsActionType.SMS_ACTION_REGIST;
      /**
       * <code>required .IM.Sms.SmsActionType action = 2;</code>
       */
      public boolean hasAction() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .IM.Sms.SmsActionType action = 2;</code>
       */
      public com.fise.xw.protobuf.IMSms.SmsActionType getAction() {
        return action_;
      }
      /**
       * <code>required .IM.Sms.SmsActionType action = 2;</code>
       */
      public Builder setAction(com.fise.xw.protobuf.IMSms.SmsActionType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        action_ = value;
        
        return this;
      }
      /**
       * <code>required .IM.Sms.SmsActionType action = 2;</code>
       */
      public Builder clearAction() {
        bitField0_ = (bitField0_ & ~0x00000002);
        action_ = com.fise.xw.protobuf.IMSms.SmsActionType.SMS_ACTION_REGIST;
        
        return this;
      }

      private java.lang.Object param_ = "";
      /**
       * <code>optional string param = 3;</code>
       */
      public boolean hasParam() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string param = 3;</code>
       */
      public java.lang.String getParam() {
        java.lang.Object ref = param_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            param_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string param = 3;</code>
       */
      public com.google.protobuf.ByteString
          getParamBytes() {
        java.lang.Object ref = param_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          param_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string param = 3;</code>
       */
      public Builder setParam(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        param_ = value;
        
        return this;
      }
      /**
       * <code>optional string param = 3;</code>
       */
      public Builder clearParam() {
        bitField0_ = (bitField0_ & ~0x00000004);
        param_ = getDefaultInstance().getParam();
        
        return this;
      }
      /**
       * <code>optional string param = 3;</code>
       */
      public Builder setParamBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        param_ = value;
        
        return this;
      }

      private com.google.protobuf.ByteString attachData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes attach_data = 20;</code>
       */
      public boolean hasAttachData() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bytes attach_data = 20;</code>
       */
      public com.google.protobuf.ByteString getAttachData() {
        return attachData_;
      }
      /**
       * <code>optional bytes attach_data = 20;</code>
       */
      public Builder setAttachData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        attachData_ = value;
        
        return this;
      }
      /**
       * <code>optional bytes attach_data = 20;</code>
       */
      public Builder clearAttachData() {
        bitField0_ = (bitField0_ & ~0x00000008);
        attachData_ = getDefaultInstance().getAttachData();
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:IM.Sms.IMSendSmsReq)
    }

    static {
      defaultInstance = new IMSendSmsReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:IM.Sms.IMSendSmsReq)
  }

  public interface IMSendSmsResOrBuilder extends
      // @@protoc_insertion_point(interface_extends:IM.Sms.IMSendSmsRes)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required uint32 server_time = 1;</code>
     *
     * <pre>
     *cmd id:	CID_SMS_SEND_RESPONSE = 0x1001
     * </pre>
     */
    boolean hasServerTime();
    /**
     * <code>required uint32 server_time = 1;</code>
     *
     * <pre>
     *cmd id:	CID_SMS_SEND_RESPONSE = 0x1001
     * </pre>
     */
    int getServerTime();

    /**
     * <code>required .IM.BaseDefine.ResultType result_code = 2;</code>
     */
    boolean hasResultCode();
    /**
     * <code>required .IM.BaseDefine.ResultType result_code = 2;</code>
     */
    com.fise.xw.protobuf.IMBaseDefine.ResultType getResultCode();

    /**
     * <code>optional string ret_msg = 3;</code>
     */
    boolean hasRetMsg();
    /**
     * <code>optional string ret_msg = 3;</code>
     */
    java.lang.String getRetMsg();
    /**
     * <code>optional string ret_msg = 3;</code>
     */
    com.google.protobuf.ByteString
        getRetMsgBytes();

    /**
     * <code>optional bytes attach_data = 20;</code>
     */
    boolean hasAttachData();
    /**
     * <code>optional bytes attach_data = 20;</code>
     */
    com.google.protobuf.ByteString getAttachData();
  }
  /**
   * Protobuf type {@code IM.Sms.IMSendSmsRes}
   */
  public static final class IMSendSmsRes extends
      com.google.protobuf.GeneratedMessageLite implements
      // @@protoc_insertion_point(message_implements:IM.Sms.IMSendSmsRes)
      IMSendSmsResOrBuilder {
    // Use IMSendSmsRes.newBuilder() to construct.
    private IMSendSmsRes(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private IMSendSmsRes(boolean noInit) { this.unknownFields = com.google.protobuf.ByteString.EMPTY;}

    private static final IMSendSmsRes defaultInstance;
    public static IMSendSmsRes getDefaultInstance() {
      return defaultInstance;
    }

    public IMSendSmsRes getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.ByteString unknownFields;
    private IMSendSmsRes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.ByteString.Output unknownFieldsOutput =
          com.google.protobuf.ByteString.newOutput();
      com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
          com.google.protobuf.CodedOutputStream.newInstance(
              unknownFieldsOutput);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              serverTime_ = input.readUInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.fise.xw.protobuf.IMBaseDefine.ResultType value = com.fise.xw.protobuf.IMBaseDefine.ResultType.valueOf(rawValue);
              if (value == null) {
                unknownFieldsCodedOutput.writeRawVarint32(tag);
                unknownFieldsCodedOutput.writeRawVarint32(rawValue);
              } else {
                bitField0_ |= 0x00000002;
                resultCode_ = value;
              }
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              retMsg_ = bs;
              break;
            }
            case 162: {
              bitField0_ |= 0x00000008;
              attachData_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        try {
          unknownFieldsCodedOutput.flush();
        } catch (java.io.IOException e) {
        // Should not happen
        } finally {
          unknownFields = unknownFieldsOutput.toByteString();
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<IMSendSmsRes> PARSER =
        new com.google.protobuf.AbstractParser<IMSendSmsRes>() {
      public IMSendSmsRes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IMSendSmsRes(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<IMSendSmsRes> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SERVER_TIME_FIELD_NUMBER = 1;
    private int serverTime_;
    /**
     * <code>required uint32 server_time = 1;</code>
     *
     * <pre>
     *cmd id:	CID_SMS_SEND_RESPONSE = 0x1001
     * </pre>
     */
    public boolean hasServerTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 server_time = 1;</code>
     *
     * <pre>
     *cmd id:	CID_SMS_SEND_RESPONSE = 0x1001
     * </pre>
     */
    public int getServerTime() {
      return serverTime_;
    }

    public static final int RESULT_CODE_FIELD_NUMBER = 2;
    private com.fise.xw.protobuf.IMBaseDefine.ResultType resultCode_;
    /**
     * <code>required .IM.BaseDefine.ResultType result_code = 2;</code>
     */
    public boolean hasResultCode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .IM.BaseDefine.ResultType result_code = 2;</code>
     */
    public com.fise.xw.protobuf.IMBaseDefine.ResultType getResultCode() {
      return resultCode_;
    }

    public static final int RET_MSG_FIELD_NUMBER = 3;
    private java.lang.Object retMsg_;
    /**
     * <code>optional string ret_msg = 3;</code>
     */
    public boolean hasRetMsg() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string ret_msg = 3;</code>
     */
    public java.lang.String getRetMsg() {
      java.lang.Object ref = retMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          retMsg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string ret_msg = 3;</code>
     */
    public com.google.protobuf.ByteString
        getRetMsgBytes() {
      java.lang.Object ref = retMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        retMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ATTACH_DATA_FIELD_NUMBER = 20;
    private com.google.protobuf.ByteString attachData_;
    /**
     * <code>optional bytes attach_data = 20;</code>
     */
    public boolean hasAttachData() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bytes attach_data = 20;</code>
     */
    public com.google.protobuf.ByteString getAttachData() {
      return attachData_;
    }

    private void initFields() {
      serverTime_ = 0;
      resultCode_ = com.fise.xw.protobuf.IMBaseDefine.ResultType.REFUSE_REASON_NONE;
      retMsg_ = "";
      attachData_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasServerTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasResultCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, serverTime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, resultCode_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getRetMsgBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(20, attachData_);
      }
      output.writeRawBytes(unknownFields);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, serverTime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, resultCode_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getRetMsgBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(20, attachData_);
      }
      size += unknownFields.size();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.fise.xw.protobuf.IMSms.IMSendSmsRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fise.xw.protobuf.IMSms.IMSendSmsRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fise.xw.protobuf.IMSms.IMSendSmsRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fise.xw.protobuf.IMSms.IMSendSmsRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fise.xw.protobuf.IMSms.IMSendSmsRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.fise.xw.protobuf.IMSms.IMSendSmsRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.fise.xw.protobuf.IMSms.IMSendSmsRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.fise.xw.protobuf.IMSms.IMSendSmsRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.fise.xw.protobuf.IMSms.IMSendSmsRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.fise.xw.protobuf.IMSms.IMSendSmsRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.fise.xw.protobuf.IMSms.IMSendSmsRes prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code IM.Sms.IMSendSmsRes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.fise.xw.protobuf.IMSms.IMSendSmsRes, Builder>
        implements
        // @@protoc_insertion_point(builder_implements:IM.Sms.IMSendSmsRes)
        com.fise.xw.protobuf.IMSms.IMSendSmsResOrBuilder {
      // Construct using com.fise.xw.protobuf.IMSms.IMSendSmsRes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        serverTime_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        resultCode_ = com.fise.xw.protobuf.IMBaseDefine.ResultType.REFUSE_REASON_NONE;
        bitField0_ = (bitField0_ & ~0x00000002);
        retMsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        attachData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.fise.xw.protobuf.IMSms.IMSendSmsRes getDefaultInstanceForType() {
        return com.fise.xw.protobuf.IMSms.IMSendSmsRes.getDefaultInstance();
      }

      public com.fise.xw.protobuf.IMSms.IMSendSmsRes build() {
        com.fise.xw.protobuf.IMSms.IMSendSmsRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.fise.xw.protobuf.IMSms.IMSendSmsRes buildPartial() {
        com.fise.xw.protobuf.IMSms.IMSendSmsRes result = new com.fise.xw.protobuf.IMSms.IMSendSmsRes(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.serverTime_ = serverTime_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.resultCode_ = resultCode_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.retMsg_ = retMsg_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.attachData_ = attachData_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.fise.xw.protobuf.IMSms.IMSendSmsRes other) {
        if (other == com.fise.xw.protobuf.IMSms.IMSendSmsRes.getDefaultInstance()) return this;
        if (other.hasServerTime()) {
          setServerTime(other.getServerTime());
        }
        if (other.hasResultCode()) {
          setResultCode(other.getResultCode());
        }
        if (other.hasRetMsg()) {
          bitField0_ |= 0x00000004;
          retMsg_ = other.retMsg_;
          
        }
        if (other.hasAttachData()) {
          setAttachData(other.getAttachData());
        }
        setUnknownFields(
            getUnknownFields().concat(other.unknownFields));
        return this;
      }

      public final boolean isInitialized() {
        if (!hasServerTime()) {
          
          return false;
        }
        if (!hasResultCode()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.fise.xw.protobuf.IMSms.IMSendSmsRes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.fise.xw.protobuf.IMSms.IMSendSmsRes) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int serverTime_ ;
      /**
       * <code>required uint32 server_time = 1;</code>
       *
       * <pre>
       *cmd id:	CID_SMS_SEND_RESPONSE = 0x1001
       * </pre>
       */
      public boolean hasServerTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 server_time = 1;</code>
       *
       * <pre>
       *cmd id:	CID_SMS_SEND_RESPONSE = 0x1001
       * </pre>
       */
      public int getServerTime() {
        return serverTime_;
      }
      /**
       * <code>required uint32 server_time = 1;</code>
       *
       * <pre>
       *cmd id:	CID_SMS_SEND_RESPONSE = 0x1001
       * </pre>
       */
      public Builder setServerTime(int value) {
        bitField0_ |= 0x00000001;
        serverTime_ = value;
        
        return this;
      }
      /**
       * <code>required uint32 server_time = 1;</code>
       *
       * <pre>
       *cmd id:	CID_SMS_SEND_RESPONSE = 0x1001
       * </pre>
       */
      public Builder clearServerTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serverTime_ = 0;
        
        return this;
      }

      private com.fise.xw.protobuf.IMBaseDefine.ResultType resultCode_ = com.fise.xw.protobuf.IMBaseDefine.ResultType.REFUSE_REASON_NONE;
      /**
       * <code>required .IM.BaseDefine.ResultType result_code = 2;</code>
       */
      public boolean hasResultCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .IM.BaseDefine.ResultType result_code = 2;</code>
       */
      public com.fise.xw.protobuf.IMBaseDefine.ResultType getResultCode() {
        return resultCode_;
      }
      /**
       * <code>required .IM.BaseDefine.ResultType result_code = 2;</code>
       */
      public Builder setResultCode(com.fise.xw.protobuf.IMBaseDefine.ResultType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        resultCode_ = value;
        
        return this;
      }
      /**
       * <code>required .IM.BaseDefine.ResultType result_code = 2;</code>
       */
      public Builder clearResultCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        resultCode_ = com.fise.xw.protobuf.IMBaseDefine.ResultType.REFUSE_REASON_NONE;
        
        return this;
      }

      private java.lang.Object retMsg_ = "";
      /**
       * <code>optional string ret_msg = 3;</code>
       */
      public boolean hasRetMsg() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string ret_msg = 3;</code>
       */
      public java.lang.String getRetMsg() {
        java.lang.Object ref = retMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            retMsg_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string ret_msg = 3;</code>
       */
      public com.google.protobuf.ByteString
          getRetMsgBytes() {
        java.lang.Object ref = retMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          retMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ret_msg = 3;</code>
       */
      public Builder setRetMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        retMsg_ = value;
        
        return this;
      }
      /**
       * <code>optional string ret_msg = 3;</code>
       */
      public Builder clearRetMsg() {
        bitField0_ = (bitField0_ & ~0x00000004);
        retMsg_ = getDefaultInstance().getRetMsg();
        
        return this;
      }
      /**
       * <code>optional string ret_msg = 3;</code>
       */
      public Builder setRetMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        retMsg_ = value;
        
        return this;
      }

      private com.google.protobuf.ByteString attachData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes attach_data = 20;</code>
       */
      public boolean hasAttachData() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bytes attach_data = 20;</code>
       */
      public com.google.protobuf.ByteString getAttachData() {
        return attachData_;
      }
      /**
       * <code>optional bytes attach_data = 20;</code>
       */
      public Builder setAttachData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        attachData_ = value;
        
        return this;
      }
      /**
       * <code>optional bytes attach_data = 20;</code>
       */
      public Builder clearAttachData() {
        bitField0_ = (bitField0_ & ~0x00000008);
        attachData_ = getDefaultInstance().getAttachData();
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:IM.Sms.IMSendSmsRes)
    }

    static {
      defaultInstance = new IMSendSmsRes(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:IM.Sms.IMSendSmsRes)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
